// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package dataplane

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfConntrackEntry struct {
	_             structs.HostLayout
	OriginalTuple bpfFlowKey
	ReplyTuple    bpfFlowKey
	Timestamp     uint64
	Status        uint32
	NatType       uint8
	Pad           [3]uint8
}

type bpfConntrackKey struct {
	_         structs.HostLayout
	SrcIp     [4]uint32
	DstIp     [4]uint32
	SrcPort   uint16
	DstPort   uint16
	Protocol  uint8
	IpVersion uint8
	Pad       uint16
}

type bpfFlowKey struct {
	_         structs.HostLayout
	SrcIp     [4]uint32
	DstIp     [4]uint32
	SrcPort   uint16
	DstPort   uint16
	Protocol  uint8
	IpVersion uint8
	VlanId    uint16
}

type bpfFragConfig struct {
	_         structs.HostLayout
	Mode      uint8
	LogEvents uint8
	Reserved  uint16
	_         [4]byte
	TimeoutNs uint64
	Reserved2 [2]uint64
}

type bpfFragKey struct {
	_         structs.HostLayout
	SrcIp     [4]uint32
	DstIp     [4]uint32
	FragId    uint32
	Protocol  uint8
	IpVersion uint8
	Reserved  uint16
}

type bpfFragValue struct {
	_            structs.HostLayout
	CompleteKey  bpfFlowKey
	Timestamp    uint64
	PolicyAction uint8
	Reserved     [7]uint8
}

type bpfIdentityPolicyKey struct {
	_           structs.HostLayout
	SrcIdentity uint32
	DstIdentity uint32
	DstPort     uint16
	Protocol    uint8
	Pad         uint8
}

type bpfIdentityPolicyValue struct {
	_          structs.HostLayout
	Action     uint8
	LogEnabled uint8
	Priority   uint16
	RuleId     uint32
	HitCount   uint64
}

type bpfIpcacheKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Ip        [16]uint8
}

type bpfIpcacheValue struct {
	_        structs.HostLayout
	Identity uint32
	Pad      [4]uint8
}

type bpfNatConfig struct {
	_               structs.HostLayout
	MatchMode       uint8
	EnableCache     uint8
	EnableBpfHelper uint8
	LogEvents       uint8
	Reserved        [4]uint32
}

type bpfNatStatsValue struct {
	_     structs.HostLayout
	Count uint64
}

type bpfPolicyKey struct {
	_         structs.HostLayout
	SrcIp     [4]uint32
	DstIp     [4]uint32
	SrcPort   uint16
	DstPort   uint16
	Protocol  uint8
	Direction uint8
	IpVersion uint8
	Pad       uint8
	VlanId    uint16
	Pad2      uint16
}

type bpfPolicyValue struct {
	_          structs.HostLayout
	Action     uint8
	LogEnabled uint8
	Priority   uint16
	RuleId     uint32
	HitCount   uint64
}

type bpfProcessCacheEntry struct {
	_           structs.HostLayout
	Comm        [16]int8
	ExecTime    uint64
	ContainerId [64]int8
}

type bpfProtocolSegment struct {
	_            structs.HostLayout
	StartIdx     uint32
	PolicyCount  uint32
	ProcessCount uint32
	Reserved     uint32
}

type bpfSessionValue struct {
	_               structs.HostLayout
	CreatedTs       uint64
	LastSeenTs      uint64
	PacketsToServer uint64
	PacketsToClient uint64
	BytesToServer   uint64
	BytesToClient   uint64
	TcpSeqClient    uint32
	TcpSeqServer    uint32
	TcpAckClient    uint32
	TcpAckServer    uint32
	TcpWindowSize   uint16
	TcpRetransCount uint8
	State           uint8
	TcpState        uint8
	PolicyAction    uint8
	Flags           uint8
	Pad             uint8
}

type bpfWildcardPolicy struct {
	_           structs.HostLayout
	SrcIp       [4]uint32
	SrcIpMask   [4]uint32
	DstIp       [4]uint32
	DstIpMask   [4]uint32
	SrcPort     uint16
	DstPort     uint16
	Protocol    uint8
	Action      uint8
	LogEnabled  uint8
	Direction   uint8
	IpVersion   uint8
	Pad         [3]uint8
	Priority    uint16
	VlanId      uint16
	RuleId      uint32
	ProcessName [16]int8
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	TcMicrosegmentFilter *ebpf.ProgramSpec `ebpf:"tc_microsegment_filter"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	ConntrackCacheMap *ebpf.MapSpec `ebpf:"conntrack_cache_map"`
	FlowEvents        *ebpf.MapSpec `ebpf:"flow_events"`
	FragConfigMap     *ebpf.MapSpec `ebpf:"frag_config_map"`
	FragStateMap      *ebpf.MapSpec `ebpf:"frag_state_map"`
	FragStatsMap      *ebpf.MapSpec `ebpf:"frag_stats_map"`
	IdentityPolicyMap *ebpf.MapSpec `ebpf:"identity_policy_map"`
	IpcacheMap        *ebpf.MapSpec `ebpf:"ipcache_map"`
	NatConfigMap      *ebpf.MapSpec `ebpf:"nat_config_map"`
	NatStatsMap       *ebpf.MapSpec `ebpf:"nat_stats_map"`
	PolicyMap         *ebpf.MapSpec `ebpf:"policy_map"`
	ProcessEvents     *ebpf.MapSpec `ebpf:"process_events"`
	ProcessInfoMap    *ebpf.MapSpec `ebpf:"process_info_map"`
	ProtocolOffsetMap *ebpf.MapSpec `ebpf:"protocol_offset_map"`
	SessionMap        *ebpf.MapSpec `ebpf:"session_map"`
	StatsMap          *ebpf.MapSpec `ebpf:"stats_map"`
	TimeoutConfigMap  *ebpf.MapSpec `ebpf:"timeout_config_map"`
	WildcardPolicyMap *ebpf.MapSpec `ebpf:"wildcard_policy_map"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	ConntrackCacheMap *ebpf.Map `ebpf:"conntrack_cache_map"`
	FlowEvents        *ebpf.Map `ebpf:"flow_events"`
	FragConfigMap     *ebpf.Map `ebpf:"frag_config_map"`
	FragStateMap      *ebpf.Map `ebpf:"frag_state_map"`
	FragStatsMap      *ebpf.Map `ebpf:"frag_stats_map"`
	IdentityPolicyMap *ebpf.Map `ebpf:"identity_policy_map"`
	IpcacheMap        *ebpf.Map `ebpf:"ipcache_map"`
	NatConfigMap      *ebpf.Map `ebpf:"nat_config_map"`
	NatStatsMap       *ebpf.Map `ebpf:"nat_stats_map"`
	PolicyMap         *ebpf.Map `ebpf:"policy_map"`
	ProcessEvents     *ebpf.Map `ebpf:"process_events"`
	ProcessInfoMap    *ebpf.Map `ebpf:"process_info_map"`
	ProtocolOffsetMap *ebpf.Map `ebpf:"protocol_offset_map"`
	SessionMap        *ebpf.Map `ebpf:"session_map"`
	StatsMap          *ebpf.Map `ebpf:"stats_map"`
	TimeoutConfigMap  *ebpf.Map `ebpf:"timeout_config_map"`
	WildcardPolicyMap *ebpf.Map `ebpf:"wildcard_policy_map"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.ConntrackCacheMap,
		m.FlowEvents,
		m.FragConfigMap,
		m.FragStateMap,
		m.FragStatsMap,
		m.IdentityPolicyMap,
		m.IpcacheMap,
		m.NatConfigMap,
		m.NatStatsMap,
		m.PolicyMap,
		m.ProcessEvents,
		m.ProcessInfoMap,
		m.ProtocolOffsetMap,
		m.SessionMap,
		m.StatsMap,
		m.TimeoutConfigMap,
		m.WildcardPolicyMap,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	TcMicrosegmentFilter *ebpf.Program `ebpf:"tc_microsegment_filter"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.TcMicrosegmentFilter,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_x86_bpfel.o
var _BpfBytes []byte
