// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package dataplane

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfFlowKey struct {
	_        structs.HostLayout
	SrcIp    uint32
	DstIp    uint32
	SrcPort  uint16
	DstPort  uint16
	Protocol uint8
	Pad      [3]uint8
}

type bpfPolicyKey struct {
	_        structs.HostLayout
	SrcIp    uint32
	DstIp    uint32
	SrcPort  uint16
	DstPort  uint16
	Protocol uint8
	Pad      [3]uint8
}

type bpfPolicyValue struct {
	_          structs.HostLayout
	Action     uint8
	LogEnabled uint8
	Priority   uint16
	RuleId     uint32
	HitCount   uint64
}

type bpfSessionValue struct {
	_               structs.HostLayout
	CreatedTs       uint64
	LastSeenTs      uint64
	PacketsToServer uint64
	PacketsToClient uint64
	BytesToServer   uint64
	BytesToClient   uint64
	State           uint8
	TcpState        uint8
	PolicyAction    uint8
	Flags           uint8
	Pad             uint32
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	TcMicrosegmentFilter *ebpf.ProgramSpec `ebpf:"tc_microsegment_filter"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	FlowEvents *ebpf.MapSpec `ebpf:"flow_events"`
	PolicyMap  *ebpf.MapSpec `ebpf:"policy_map"`
	SessionMap *ebpf.MapSpec `ebpf:"session_map"`
	StatsMap   *ebpf.MapSpec `ebpf:"stats_map"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	FlowEvents *ebpf.Map `ebpf:"flow_events"`
	PolicyMap  *ebpf.Map `ebpf:"policy_map"`
	SessionMap *ebpf.Map `ebpf:"session_map"`
	StatsMap   *ebpf.Map `ebpf:"stats_map"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.FlowEvents,
		m.PolicyMap,
		m.SessionMap,
		m.StatsMap,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	TcMicrosegmentFilter *ebpf.Program `ebpf:"tc_microsegment_filter"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.TcMicrosegmentFilter,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_x86_bpfel.o
var _BpfBytes []byte
