// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package dataplane

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type xdpbpfConntrackEntry struct {
	_             structs.HostLayout
	OriginalTuple xdpbpfFlowKey
	ReplyTuple    xdpbpfFlowKey
	Timestamp     uint64
	Status        uint32
	NatType       uint8
	Pad           [3]uint8
}

type xdpbpfConntrackKey struct {
	_         structs.HostLayout
	SrcIp     [4]uint32
	DstIp     [4]uint32
	SrcPort   uint16
	DstPort   uint16
	Protocol  uint8
	IpVersion uint8
	Pad       uint16
}

type xdpbpfFlowKey struct {
	_         structs.HostLayout
	SrcIp     [4]uint32
	DstIp     [4]uint32
	SrcPort   uint16
	DstPort   uint16
	Protocol  uint8
	IpVersion uint8
	VlanId    uint16
}

type xdpbpfFragConfig struct {
	_         structs.HostLayout
	Mode      uint8
	LogEvents uint8
	Reserved  uint16
	_         [4]byte
	TimeoutNs uint64
	Reserved2 [2]uint64
}

type xdpbpfFragKey struct {
	_         structs.HostLayout
	SrcIp     [4]uint32
	DstIp     [4]uint32
	FragId    uint32
	Protocol  uint8
	IpVersion uint8
	Reserved  uint16
}

type xdpbpfFragValue struct {
	_            structs.HostLayout
	CompleteKey  xdpbpfFlowKey
	Timestamp    uint64
	PolicyAction uint8
	Reserved     [7]uint8
}

type xdpbpfNatConfig struct {
	_               structs.HostLayout
	MatchMode       uint8
	EnableCache     uint8
	EnableBpfHelper uint8
	LogEvents       uint8
	Reserved        [4]uint32
}

type xdpbpfNatStatsValue struct {
	_     structs.HostLayout
	Count uint64
}

type xdpbpfPolicyKey struct {
	_         structs.HostLayout
	SrcIp     [4]uint32
	DstIp     [4]uint32
	SrcPort   uint16
	DstPort   uint16
	Protocol  uint8
	Direction uint8
	IpVersion uint8
	Pad       uint8
	VlanId    uint16
	Pad2      uint16
}

type xdpbpfPolicyValue struct {
	_          structs.HostLayout
	Action     uint8
	LogEnabled uint8
	Priority   uint16
	RuleId     uint32
	HitCount   uint64
}

type xdpbpfProcessCacheEntry struct {
	_           structs.HostLayout
	Comm        [16]int8
	ExecTime    uint64
	ContainerId [64]int8
}

type xdpbpfProtocolSegment struct {
	_           structs.HostLayout
	StartIdx    uint32
	PolicyCount uint32
	Reserved    [2]uint32
}

type xdpbpfSessionValue struct {
	_               structs.HostLayout
	CreatedTs       uint64
	LastSeenTs      uint64
	PacketsToServer uint64
	PacketsToClient uint64
	BytesToServer   uint64
	BytesToClient   uint64
	TcpSeqClient    uint32
	TcpSeqServer    uint32
	TcpAckClient    uint32
	TcpAckServer    uint32
	TcpWindowSize   uint16
	TcpRetransCount uint8
	State           uint8
	TcpState        uint8
	PolicyAction    uint8
	Flags           uint8
	Pad             uint8
}

type xdpbpfWildcardPolicy struct {
	_           structs.HostLayout
	SrcIp       [4]uint32
	SrcIpMask   [4]uint32
	DstIp       [4]uint32
	DstIpMask   [4]uint32
	SrcPort     uint16
	DstPort     uint16
	Protocol    uint8
	Action      uint8
	LogEnabled  uint8
	Direction   uint8
	IpVersion   uint8
	Pad         [3]uint8
	Priority    uint16
	VlanId      uint16
	RuleId      uint32
	ProcessName [16]int8
}

// loadXdpbpf returns the embedded CollectionSpec for xdpbpf.
func loadXdpbpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_XdpbpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load xdpbpf: %w", err)
	}

	return spec, err
}

// loadXdpbpfObjects loads xdpbpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*xdpbpfObjects
//	*xdpbpfPrograms
//	*xdpbpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadXdpbpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadXdpbpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// xdpbpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpbpfSpecs struct {
	xdpbpfProgramSpecs
	xdpbpfMapSpecs
	xdpbpfVariableSpecs
}

// xdpbpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpbpfProgramSpecs struct {
	XdpMicrosegmentProg *ebpf.ProgramSpec `ebpf:"xdp_microsegment_prog"`
}

// xdpbpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpbpfMapSpecs struct {
	ConntrackCacheMap *ebpf.MapSpec `ebpf:"conntrack_cache_map"`
	FlowEvents        *ebpf.MapSpec `ebpf:"flow_events"`
	FragConfigMap     *ebpf.MapSpec `ebpf:"frag_config_map"`
	FragStateMap      *ebpf.MapSpec `ebpf:"frag_state_map"`
	FragStatsMap      *ebpf.MapSpec `ebpf:"frag_stats_map"`
	NatConfigMap      *ebpf.MapSpec `ebpf:"nat_config_map"`
	NatStatsMap       *ebpf.MapSpec `ebpf:"nat_stats_map"`
	PolicyMap         *ebpf.MapSpec `ebpf:"policy_map"`
	ProcessEvents     *ebpf.MapSpec `ebpf:"process_events"`
	ProcessInfoMap    *ebpf.MapSpec `ebpf:"process_info_map"`
	ProtocolOffsetMap *ebpf.MapSpec `ebpf:"protocol_offset_map"`
	SessionMap        *ebpf.MapSpec `ebpf:"session_map"`
	StatsMap          *ebpf.MapSpec `ebpf:"stats_map"`
	TimeoutConfigMap  *ebpf.MapSpec `ebpf:"timeout_config_map"`
	WildcardPolicyMap *ebpf.MapSpec `ebpf:"wildcard_policy_map"`
}

// xdpbpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpbpfVariableSpecs struct {
}

// xdpbpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadXdpbpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpbpfObjects struct {
	xdpbpfPrograms
	xdpbpfMaps
	xdpbpfVariables
}

func (o *xdpbpfObjects) Close() error {
	return _XdpbpfClose(
		&o.xdpbpfPrograms,
		&o.xdpbpfMaps,
	)
}

// xdpbpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadXdpbpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpbpfMaps struct {
	ConntrackCacheMap *ebpf.Map `ebpf:"conntrack_cache_map"`
	FlowEvents        *ebpf.Map `ebpf:"flow_events"`
	FragConfigMap     *ebpf.Map `ebpf:"frag_config_map"`
	FragStateMap      *ebpf.Map `ebpf:"frag_state_map"`
	FragStatsMap      *ebpf.Map `ebpf:"frag_stats_map"`
	NatConfigMap      *ebpf.Map `ebpf:"nat_config_map"`
	NatStatsMap       *ebpf.Map `ebpf:"nat_stats_map"`
	PolicyMap         *ebpf.Map `ebpf:"policy_map"`
	ProcessEvents     *ebpf.Map `ebpf:"process_events"`
	ProcessInfoMap    *ebpf.Map `ebpf:"process_info_map"`
	ProtocolOffsetMap *ebpf.Map `ebpf:"protocol_offset_map"`
	SessionMap        *ebpf.Map `ebpf:"session_map"`
	StatsMap          *ebpf.Map `ebpf:"stats_map"`
	TimeoutConfigMap  *ebpf.Map `ebpf:"timeout_config_map"`
	WildcardPolicyMap *ebpf.Map `ebpf:"wildcard_policy_map"`
}

func (m *xdpbpfMaps) Close() error {
	return _XdpbpfClose(
		m.ConntrackCacheMap,
		m.FlowEvents,
		m.FragConfigMap,
		m.FragStateMap,
		m.FragStatsMap,
		m.NatConfigMap,
		m.NatStatsMap,
		m.PolicyMap,
		m.ProcessEvents,
		m.ProcessInfoMap,
		m.ProtocolOffsetMap,
		m.SessionMap,
		m.StatsMap,
		m.TimeoutConfigMap,
		m.WildcardPolicyMap,
	)
}

// xdpbpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadXdpbpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpbpfVariables struct {
}

// xdpbpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadXdpbpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpbpfPrograms struct {
	XdpMicrosegmentProg *ebpf.Program `ebpf:"xdp_microsegment_prog"`
}

func (p *xdpbpfPrograms) Close() error {
	return _XdpbpfClose(
		p.XdpMicrosegmentProg,
	)
}

func _XdpbpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xdpbpf_x86_bpfel.o
var _XdpbpfBytes []byte
