// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package dataplane

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type xdpbpfFlowKey struct {
	_        structs.HostLayout
	SrcIp    uint32
	DstIp    uint32
	SrcPort  uint16
	DstPort  uint16
	Protocol uint8
	Pad      [3]uint8
}

type xdpbpfPolicyKey struct {
	_        structs.HostLayout
	SrcIp    uint32
	DstIp    uint32
	SrcPort  uint16
	DstPort  uint16
	Protocol uint8
	Pad      [3]uint8
}

type xdpbpfPolicyValue struct {
	_          structs.HostLayout
	Action     uint8
	LogEnabled uint8
	Priority   uint16
	RuleId     uint32
	HitCount   uint64
}

type xdpbpfSessionValue struct {
	_               structs.HostLayout
	CreatedTs       uint64
	LastSeenTs      uint64
	PacketsToServer uint64
	PacketsToClient uint64
	BytesToServer   uint64
	BytesToClient   uint64
	State           uint8
	TcpState        uint8
	PolicyAction    uint8
	Flags           uint8
	Pad             uint32
}

type xdpbpfWildcardPolicy struct {
	_          structs.HostLayout
	SrcIp      uint32
	SrcIpMask  uint32
	DstIp      uint32
	DstIpMask  uint32
	SrcPort    uint16
	DstPort    uint16
	Protocol   uint8
	Action     uint8
	LogEnabled uint8
	Pad1       uint8
	Priority   uint16
	Pad2       uint16
	RuleId     uint32
}

// loadXdpbpf returns the embedded CollectionSpec for xdpbpf.
func loadXdpbpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_XdpbpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load xdpbpf: %w", err)
	}

	return spec, err
}

// loadXdpbpfObjects loads xdpbpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*xdpbpfObjects
//	*xdpbpfPrograms
//	*xdpbpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadXdpbpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadXdpbpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// xdpbpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpbpfSpecs struct {
	xdpbpfProgramSpecs
	xdpbpfMapSpecs
	xdpbpfVariableSpecs
}

// xdpbpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpbpfProgramSpecs struct {
	XdpMicrosegmentProg *ebpf.ProgramSpec `ebpf:"xdp_microsegment_prog"`
}

// xdpbpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpbpfMapSpecs struct {
	FlowEvents        *ebpf.MapSpec `ebpf:"flow_events"`
	PolicyMap         *ebpf.MapSpec `ebpf:"policy_map"`
	SessionMap        *ebpf.MapSpec `ebpf:"session_map"`
	StatsMap          *ebpf.MapSpec `ebpf:"stats_map"`
	WildcardPolicyMap *ebpf.MapSpec `ebpf:"wildcard_policy_map"`
}

// xdpbpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpbpfVariableSpecs struct {
}

// xdpbpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadXdpbpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpbpfObjects struct {
	xdpbpfPrograms
	xdpbpfMaps
	xdpbpfVariables
}

func (o *xdpbpfObjects) Close() error {
	return _XdpbpfClose(
		&o.xdpbpfPrograms,
		&o.xdpbpfMaps,
	)
}

// xdpbpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadXdpbpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpbpfMaps struct {
	FlowEvents        *ebpf.Map `ebpf:"flow_events"`
	PolicyMap         *ebpf.Map `ebpf:"policy_map"`
	SessionMap        *ebpf.Map `ebpf:"session_map"`
	StatsMap          *ebpf.Map `ebpf:"stats_map"`
	WildcardPolicyMap *ebpf.Map `ebpf:"wildcard_policy_map"`
}

func (m *xdpbpfMaps) Close() error {
	return _XdpbpfClose(
		m.FlowEvents,
		m.PolicyMap,
		m.SessionMap,
		m.StatsMap,
		m.WildcardPolicyMap,
	)
}

// xdpbpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadXdpbpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpbpfVariables struct {
}

// xdpbpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadXdpbpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpbpfPrograms struct {
	XdpMicrosegmentProg *ebpf.Program `ebpf:"xdp_microsegment_prog"`
}

func (p *xdpbpfPrograms) Close() error {
	return _XdpbpfClose(
		p.XdpMicrosegmentProg,
	)
}

func _XdpbpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xdpbpf_x86_bpfel.o
var _XdpbpfBytes []byte
