// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: alert/alert.proto

package alert

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	common "github.com/haolipeng/ebpf-based-microsegment/api/proto/common"
	flow "github.com/haolipeng/ebpf-based-microsegment/api/proto/flow"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AlertLevel defines alert severity levels
type AlertLevel int32

const (
	// Informational alert (low priority)
	AlertLevel_ALERT_INFO AlertLevel = 0
	// Warning - potential security concern
	AlertLevel_ALERT_WARNING AlertLevel = 1
	// Critical - immediate security threat
	AlertLevel_ALERT_CRITICAL AlertLevel = 2
)

// Enum value maps for AlertLevel.
var (
	AlertLevel_name = map[int32]string{
		0: "ALERT_INFO",
		1: "ALERT_WARNING",
		2: "ALERT_CRITICAL",
	}
	AlertLevel_value = map[string]int32{
		"ALERT_INFO":     0,
		"ALERT_WARNING":  1,
		"ALERT_CRITICAL": 2,
	}
)

func (x AlertLevel) Enum() *AlertLevel {
	p := new(AlertLevel)
	*p = x
	return p
}

func (x AlertLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_alert_alert_proto_enumTypes[0].Descriptor()
}

func (AlertLevel) Type() protoreflect.EnumType {
	return &file_alert_alert_proto_enumTypes[0]
}

func (x AlertLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertLevel.Descriptor instead.
func (AlertLevel) EnumDescriptor() ([]byte, []int) {
	return file_alert_alert_proto_rawDescGZIP(), []int{0}
}

// AlertType categorizes different types of security alerts
type AlertType int32

const (
	// Process running from suspicious directory (e.g., /tmp)
	AlertType_ALERT_SUSPICIOUS_PATH AlertType = 0
	// Privileged process from untrusted location
	AlertType_ALERT_PRIVILEGE_ESCALATION AlertType = 1
	// Process name doesn't match executable path
	AlertType_ALERT_NAME_MISMATCH AlertType = 2
	// Anomalous network connection from process
	AlertType_ALERT_ANOMALOUS_CONNECTION AlertType = 3
	// Process running from deleted executable
	AlertType_ALERT_DELETED_EXECUTABLE AlertType = 4
	// Process running from hidden file
	AlertType_ALERT_HIDDEN_EXECUTABLE AlertType = 5
)

// Enum value maps for AlertType.
var (
	AlertType_name = map[int32]string{
		0: "ALERT_SUSPICIOUS_PATH",
		1: "ALERT_PRIVILEGE_ESCALATION",
		2: "ALERT_NAME_MISMATCH",
		3: "ALERT_ANOMALOUS_CONNECTION",
		4: "ALERT_DELETED_EXECUTABLE",
		5: "ALERT_HIDDEN_EXECUTABLE",
	}
	AlertType_value = map[string]int32{
		"ALERT_SUSPICIOUS_PATH":      0,
		"ALERT_PRIVILEGE_ESCALATION": 1,
		"ALERT_NAME_MISMATCH":        2,
		"ALERT_ANOMALOUS_CONNECTION": 3,
		"ALERT_DELETED_EXECUTABLE":   4,
		"ALERT_HIDDEN_EXECUTABLE":    5,
	}
)

func (x AlertType) Enum() *AlertType {
	p := new(AlertType)
	*p = x
	return p
}

func (x AlertType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertType) Descriptor() protoreflect.EnumDescriptor {
	return file_alert_alert_proto_enumTypes[1].Descriptor()
}

func (AlertType) Type() protoreflect.EnumType {
	return &file_alert_alert_proto_enumTypes[1]
}

func (x AlertType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertType.Descriptor instead.
func (AlertType) EnumDescriptor() ([]byte, []int) {
	return file_alert_alert_proto_rawDescGZIP(), []int{1}
}

// SecurityAlert represents a security alert event
// Generated when suspicious process activity is detected
type SecurityAlert struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique alert ID (UUID)
	AlertId string `protobuf:"bytes,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	// Alert severity level
	Level AlertLevel `protobuf:"varint,2,opt,name=level,proto3,enum=microsegment.alert.AlertLevel" json:"level,omitempty"`
	// Alert type/category
	Type AlertType `protobuf:"varint,3,opt,name=type,proto3,enum=microsegment.alert.AlertType" json:"type,omitempty"`
	// Process information that triggered the alert
	ProcessInfo *flow.ProcessInfo `protobuf:"bytes,4,opt,name=process_info,json=processInfo,proto3" json:"process_info,omitempty"`
	// Associated network flow (optional, may be null for process-only alerts)
	FlowEvent *flow.FlowEvent `protobuf:"bytes,5,opt,name=flow_event,json=flowEvent,proto3" json:"flow_event,omitempty"`
	// Human-readable reason/description
	Reason string `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	// Alert generation timestamp (Unix nanoseconds)
	Timestamp int64 `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Agent ID that generated the alert
	AgentId string `protobuf:"bytes,8,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Additional context metadata
	Metadata      map[string]string `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityAlert) Reset() {
	*x = SecurityAlert{}
	mi := &file_alert_alert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityAlert) ProtoMessage() {}

func (x *SecurityAlert) ProtoReflect() protoreflect.Message {
	mi := &file_alert_alert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityAlert.ProtoReflect.Descriptor instead.
func (*SecurityAlert) Descriptor() ([]byte, []int) {
	return file_alert_alert_proto_rawDescGZIP(), []int{0}
}

func (x *SecurityAlert) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

func (x *SecurityAlert) GetLevel() AlertLevel {
	if x != nil {
		return x.Level
	}
	return AlertLevel_ALERT_INFO
}

func (x *SecurityAlert) GetType() AlertType {
	if x != nil {
		return x.Type
	}
	return AlertType_ALERT_SUSPICIOUS_PATH
}

func (x *SecurityAlert) GetProcessInfo() *flow.ProcessInfo {
	if x != nil {
		return x.ProcessInfo
	}
	return nil
}

func (x *SecurityAlert) GetFlowEvent() *flow.FlowEvent {
	if x != nil {
		return x.FlowEvent
	}
	return nil
}

func (x *SecurityAlert) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SecurityAlert) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SecurityAlert) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SecurityAlert) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// AlertQuery specifies filtering criteria for alert queries
type AlertQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Time range filter
	TimeRange *common.TimeRange `protobuf:"bytes,1,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	// Filter by alert level (minimum level)
	MinLevel AlertLevel `protobuf:"varint,2,opt,name=min_level,json=minLevel,proto3,enum=microsegment.alert.AlertLevel" json:"min_level,omitempty"`
	// Filter by alert type
	Type AlertType `protobuf:"varint,3,opt,name=type,proto3,enum=microsegment.alert.AlertType" json:"type,omitempty"`
	// Filter by process ID
	Pid uint32 `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`
	// Filter by process name
	ProcessName string `protobuf:"bytes,5,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	// Filter by process path prefix
	ProcessPath string `protobuf:"bytes,6,opt,name=process_path,json=processPath,proto3" json:"process_path,omitempty"`
	// Filter by agent ID
	AgentId string `protobuf:"bytes,7,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Filter by container ID
	ContainerId string `protobuf:"bytes,8,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// Maximum number of results (0 = unlimited)
	Limit uint32 `protobuf:"varint,9,opt,name=limit,proto3" json:"limit,omitempty"`
	// Offset for pagination
	Offset        uint32 `protobuf:"varint,10,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertQuery) Reset() {
	*x = AlertQuery{}
	mi := &file_alert_alert_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertQuery) ProtoMessage() {}

func (x *AlertQuery) ProtoReflect() protoreflect.Message {
	mi := &file_alert_alert_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertQuery.ProtoReflect.Descriptor instead.
func (*AlertQuery) Descriptor() ([]byte, []int) {
	return file_alert_alert_proto_rawDescGZIP(), []int{1}
}

func (x *AlertQuery) GetTimeRange() *common.TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

func (x *AlertQuery) GetMinLevel() AlertLevel {
	if x != nil {
		return x.MinLevel
	}
	return AlertLevel_ALERT_INFO
}

func (x *AlertQuery) GetType() AlertType {
	if x != nil {
		return x.Type
	}
	return AlertType_ALERT_SUSPICIOUS_PATH
}

func (x *AlertQuery) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *AlertQuery) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *AlertQuery) GetProcessPath() string {
	if x != nil {
		return x.ProcessPath
	}
	return ""
}

func (x *AlertQuery) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AlertQuery) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *AlertQuery) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *AlertQuery) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// AlertQueryResponse contains the results of an alert query
type AlertQueryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Matching alerts
	Alerts []*SecurityAlert `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	// Total count (before limit/offset)
	TotalCount uint64 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	// Whether there are more results available
	HasMore       bool `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertQueryResponse) Reset() {
	*x = AlertQueryResponse{}
	mi := &file_alert_alert_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertQueryResponse) ProtoMessage() {}

func (x *AlertQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alert_alert_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertQueryResponse.ProtoReflect.Descriptor instead.
func (*AlertQueryResponse) Descriptor() ([]byte, []int) {
	return file_alert_alert_proto_rawDescGZIP(), []int{2}
}

func (x *AlertQueryResponse) GetAlerts() []*SecurityAlert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

func (x *AlertQueryResponse) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *AlertQueryResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// AlertSummaryRequest specifies parameters for alert summary
type AlertSummaryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Time range for aggregation
	TimeRange *common.TimeRange `protobuf:"bytes,1,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	// Group by alert type
	GroupByType bool `protobuf:"varint,2,opt,name=group_by_type,json=groupByType,proto3" json:"group_by_type,omitempty"`
	// Group by alert level
	GroupByLevel bool `protobuf:"varint,3,opt,name=group_by_level,json=groupByLevel,proto3" json:"group_by_level,omitempty"`
	// Optional filters
	AgentId       string     `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	MinLevel      AlertLevel `protobuf:"varint,5,opt,name=min_level,json=minLevel,proto3,enum=microsegment.alert.AlertLevel" json:"min_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertSummaryRequest) Reset() {
	*x = AlertSummaryRequest{}
	mi := &file_alert_alert_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertSummaryRequest) ProtoMessage() {}

func (x *AlertSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_alert_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertSummaryRequest.ProtoReflect.Descriptor instead.
func (*AlertSummaryRequest) Descriptor() ([]byte, []int) {
	return file_alert_alert_proto_rawDescGZIP(), []int{3}
}

func (x *AlertSummaryRequest) GetTimeRange() *common.TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

func (x *AlertSummaryRequest) GetGroupByType() bool {
	if x != nil {
		return x.GroupByType
	}
	return false
}

func (x *AlertSummaryRequest) GetGroupByLevel() bool {
	if x != nil {
		return x.GroupByLevel
	}
	return false
}

func (x *AlertSummaryRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AlertSummaryRequest) GetMinLevel() AlertLevel {
	if x != nil {
		return x.MinLevel
	}
	return AlertLevel_ALERT_INFO
}

// AlertSummary contains aggregated alert statistics
type AlertSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total number of alerts
	TotalAlerts uint64 `protobuf:"varint,1,opt,name=total_alerts,json=totalAlerts,proto3" json:"total_alerts,omitempty"`
	// Count by level
	CriticalCount uint64 `protobuf:"varint,2,opt,name=critical_count,json=criticalCount,proto3" json:"critical_count,omitempty"`
	WarningCount  uint64 `protobuf:"varint,3,opt,name=warning_count,json=warningCount,proto3" json:"warning_count,omitempty"`
	InfoCount     uint64 `protobuf:"varint,4,opt,name=info_count,json=infoCount,proto3" json:"info_count,omitempty"`
	// Alert statistics by type
	TypeStats []*AlertTypeStats `protobuf:"bytes,5,rep,name=type_stats,json=typeStats,proto3" json:"type_stats,omitempty"`
	// Top suspicious processes
	TopProcesses  []*ProcessAlertStats `protobuf:"bytes,6,rep,name=top_processes,json=topProcesses,proto3" json:"top_processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertSummary) Reset() {
	*x = AlertSummary{}
	mi := &file_alert_alert_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertSummary) ProtoMessage() {}

func (x *AlertSummary) ProtoReflect() protoreflect.Message {
	mi := &file_alert_alert_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertSummary.ProtoReflect.Descriptor instead.
func (*AlertSummary) Descriptor() ([]byte, []int) {
	return file_alert_alert_proto_rawDescGZIP(), []int{4}
}

func (x *AlertSummary) GetTotalAlerts() uint64 {
	if x != nil {
		return x.TotalAlerts
	}
	return 0
}

func (x *AlertSummary) GetCriticalCount() uint64 {
	if x != nil {
		return x.CriticalCount
	}
	return 0
}

func (x *AlertSummary) GetWarningCount() uint64 {
	if x != nil {
		return x.WarningCount
	}
	return 0
}

func (x *AlertSummary) GetInfoCount() uint64 {
	if x != nil {
		return x.InfoCount
	}
	return 0
}

func (x *AlertSummary) GetTypeStats() []*AlertTypeStats {
	if x != nil {
		return x.TypeStats
	}
	return nil
}

func (x *AlertSummary) GetTopProcesses() []*ProcessAlertStats {
	if x != nil {
		return x.TopProcesses
	}
	return nil
}

// AlertTypeStats contains statistics for a specific alert type
type AlertTypeStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Alert type
	Type AlertType `protobuf:"varint,1,opt,name=type,proto3,enum=microsegment.alert.AlertType" json:"type,omitempty"`
	// Number of alerts
	Count uint64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// Most recent alert timestamp
	LastSeen      int64 `protobuf:"varint,3,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertTypeStats) Reset() {
	*x = AlertTypeStats{}
	mi := &file_alert_alert_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertTypeStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertTypeStats) ProtoMessage() {}

func (x *AlertTypeStats) ProtoReflect() protoreflect.Message {
	mi := &file_alert_alert_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertTypeStats.ProtoReflect.Descriptor instead.
func (*AlertTypeStats) Descriptor() ([]byte, []int) {
	return file_alert_alert_proto_rawDescGZIP(), []int{5}
}

func (x *AlertTypeStats) GetType() AlertType {
	if x != nil {
		return x.Type
	}
	return AlertType_ALERT_SUSPICIOUS_PATH
}

func (x *AlertTypeStats) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AlertTypeStats) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

// ProcessAlertStats contains alert statistics for a specific process
type ProcessAlertStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Process executable path
	ExePath string `protobuf:"bytes,1,opt,name=exe_path,json=exePath,proto3" json:"exe_path,omitempty"`
	// Process command name
	Comm string `protobuf:"bytes,2,opt,name=comm,proto3" json:"comm,omitempty"`
	// Number of alerts for this process
	AlertCount uint64 `protobuf:"varint,3,opt,name=alert_count,json=alertCount,proto3" json:"alert_count,omitempty"`
	// Highest severity level seen
	MaxLevel AlertLevel `protobuf:"varint,4,opt,name=max_level,json=maxLevel,proto3,enum=microsegment.alert.AlertLevel" json:"max_level,omitempty"`
	// Last alert timestamp
	LastSeen      int64 `protobuf:"varint,5,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessAlertStats) Reset() {
	*x = ProcessAlertStats{}
	mi := &file_alert_alert_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessAlertStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessAlertStats) ProtoMessage() {}

func (x *ProcessAlertStats) ProtoReflect() protoreflect.Message {
	mi := &file_alert_alert_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessAlertStats.ProtoReflect.Descriptor instead.
func (*ProcessAlertStats) Descriptor() ([]byte, []int) {
	return file_alert_alert_proto_rawDescGZIP(), []int{6}
}

func (x *ProcessAlertStats) GetExePath() string {
	if x != nil {
		return x.ExePath
	}
	return ""
}

func (x *ProcessAlertStats) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

func (x *ProcessAlertStats) GetAlertCount() uint64 {
	if x != nil {
		return x.AlertCount
	}
	return 0
}

func (x *ProcessAlertStats) GetMaxLevel() AlertLevel {
	if x != nil {
		return x.MaxLevel
	}
	return AlertLevel_ALERT_INFO
}

func (x *ProcessAlertStats) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

var File_alert_alert_proto protoreflect.FileDescriptor

const file_alert_alert_proto_rawDesc = "" +
	"\n" +
	"\x11alert/alert.proto\x12\x12microsegment.alert\x1a\x13common/common.proto\x1a\x0fflow/flow.proto\"\xee\x03\n" +
	"\rSecurityAlert\x12\x19\n" +
	"\balert_id\x18\x01 \x01(\tR\aalertId\x124\n" +
	"\x05level\x18\x02 \x01(\x0e2\x1e.microsegment.alert.AlertLevelR\x05level\x121\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1d.microsegment.alert.AlertTypeR\x04type\x12A\n" +
	"\fprocess_info\x18\x04 \x01(\v2\x1e.microsegment.flow.ProcessInfoR\vprocessInfo\x12;\n" +
	"\n" +
	"flow_event\x18\x05 \x01(\v2\x1c.microsegment.flow.FlowEventR\tflowEvent\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12\x19\n" +
	"\bagent_id\x18\b \x01(\tR\aagentId\x12K\n" +
	"\bmetadata\x18\t \x03(\v2/.microsegment.alert.SecurityAlert.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xff\x02\n" +
	"\n" +
	"AlertQuery\x12=\n" +
	"\n" +
	"time_range\x18\x01 \x01(\v2\x1e.microsegment.common.TimeRangeR\ttimeRange\x12;\n" +
	"\tmin_level\x18\x02 \x01(\x0e2\x1e.microsegment.alert.AlertLevelR\bminLevel\x121\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1d.microsegment.alert.AlertTypeR\x04type\x12\x10\n" +
	"\x03pid\x18\x04 \x01(\rR\x03pid\x12!\n" +
	"\fprocess_name\x18\x05 \x01(\tR\vprocessName\x12!\n" +
	"\fprocess_path\x18\x06 \x01(\tR\vprocessPath\x12\x19\n" +
	"\bagent_id\x18\a \x01(\tR\aagentId\x12!\n" +
	"\fcontainer_id\x18\b \x01(\tR\vcontainerId\x12\x14\n" +
	"\x05limit\x18\t \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\n" +
	" \x01(\rR\x06offset\"\x8b\x01\n" +
	"\x12AlertQueryResponse\x129\n" +
	"\x06alerts\x18\x01 \x03(\v2!.microsegment.alert.SecurityAlertR\x06alerts\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x04R\n" +
	"totalCount\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"\xf6\x01\n" +
	"\x13AlertSummaryRequest\x12=\n" +
	"\n" +
	"time_range\x18\x01 \x01(\v2\x1e.microsegment.common.TimeRangeR\ttimeRange\x12\"\n" +
	"\rgroup_by_type\x18\x02 \x01(\bR\vgroupByType\x12$\n" +
	"\x0egroup_by_level\x18\x03 \x01(\bR\fgroupByLevel\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x12;\n" +
	"\tmin_level\x18\x05 \x01(\x0e2\x1e.microsegment.alert.AlertLevelR\bminLevel\"\xab\x02\n" +
	"\fAlertSummary\x12!\n" +
	"\ftotal_alerts\x18\x01 \x01(\x04R\vtotalAlerts\x12%\n" +
	"\x0ecritical_count\x18\x02 \x01(\x04R\rcriticalCount\x12#\n" +
	"\rwarning_count\x18\x03 \x01(\x04R\fwarningCount\x12\x1d\n" +
	"\n" +
	"info_count\x18\x04 \x01(\x04R\tinfoCount\x12A\n" +
	"\n" +
	"type_stats\x18\x05 \x03(\v2\".microsegment.alert.AlertTypeStatsR\ttypeStats\x12J\n" +
	"\rtop_processes\x18\x06 \x03(\v2%.microsegment.alert.ProcessAlertStatsR\ftopProcesses\"v\n" +
	"\x0eAlertTypeStats\x121\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1d.microsegment.alert.AlertTypeR\x04type\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\x12\x1b\n" +
	"\tlast_seen\x18\x03 \x01(\x03R\blastSeen\"\xbd\x01\n" +
	"\x11ProcessAlertStats\x12\x19\n" +
	"\bexe_path\x18\x01 \x01(\tR\aexePath\x12\x12\n" +
	"\x04comm\x18\x02 \x01(\tR\x04comm\x12\x1f\n" +
	"\valert_count\x18\x03 \x01(\x04R\n" +
	"alertCount\x12;\n" +
	"\tmax_level\x18\x04 \x01(\x0e2\x1e.microsegment.alert.AlertLevelR\bmaxLevel\x12\x1b\n" +
	"\tlast_seen\x18\x05 \x01(\x03R\blastSeen*C\n" +
	"\n" +
	"AlertLevel\x12\x0e\n" +
	"\n" +
	"ALERT_INFO\x10\x00\x12\x11\n" +
	"\rALERT_WARNING\x10\x01\x12\x12\n" +
	"\x0eALERT_CRITICAL\x10\x02*\xba\x01\n" +
	"\tAlertType\x12\x19\n" +
	"\x15ALERT_SUSPICIOUS_PATH\x10\x00\x12\x1e\n" +
	"\x1aALERT_PRIVILEGE_ESCALATION\x10\x01\x12\x17\n" +
	"\x13ALERT_NAME_MISMATCH\x10\x02\x12\x1e\n" +
	"\x1aALERT_ANOMALOUS_CONNECTION\x10\x03\x12\x1c\n" +
	"\x18ALERT_DELETED_EXECUTABLE\x10\x04\x12\x1b\n" +
	"\x17ALERT_HIDDEN_EXECUTABLE\x10\x052\x9d\x02\n" +
	"\fAlertService\x12X\n" +
	"\fReportAlerts\x12!.microsegment.alert.SecurityAlert\x1a#.microsegment.common.ReportResponse(\x01\x12U\n" +
	"\vQueryAlerts\x12\x1e.microsegment.alert.AlertQuery\x1a&.microsegment.alert.AlertQueryResponse\x12\\\n" +
	"\x0fGetAlertSummary\x12'.microsegment.alert.AlertSummaryRequest\x1a .microsegment.alert.AlertSummaryB>Z<github.com/haolipeng/ebpf-based-microsegment/api/proto/alertb\x06proto3"

var (
	file_alert_alert_proto_rawDescOnce sync.Once
	file_alert_alert_proto_rawDescData []byte
)

func file_alert_alert_proto_rawDescGZIP() []byte {
	file_alert_alert_proto_rawDescOnce.Do(func() {
		file_alert_alert_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alert_alert_proto_rawDesc), len(file_alert_alert_proto_rawDesc)))
	})
	return file_alert_alert_proto_rawDescData
}

var file_alert_alert_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_alert_alert_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_alert_alert_proto_goTypes = []any{
	(AlertLevel)(0),               // 0: microsegment.alert.AlertLevel
	(AlertType)(0),                // 1: microsegment.alert.AlertType
	(*SecurityAlert)(nil),         // 2: microsegment.alert.SecurityAlert
	(*AlertQuery)(nil),            // 3: microsegment.alert.AlertQuery
	(*AlertQueryResponse)(nil),    // 4: microsegment.alert.AlertQueryResponse
	(*AlertSummaryRequest)(nil),   // 5: microsegment.alert.AlertSummaryRequest
	(*AlertSummary)(nil),          // 6: microsegment.alert.AlertSummary
	(*AlertTypeStats)(nil),        // 7: microsegment.alert.AlertTypeStats
	(*ProcessAlertStats)(nil),     // 8: microsegment.alert.ProcessAlertStats
	nil,                           // 9: microsegment.alert.SecurityAlert.MetadataEntry
	(*flow.ProcessInfo)(nil),      // 10: microsegment.flow.ProcessInfo
	(*flow.FlowEvent)(nil),        // 11: microsegment.flow.FlowEvent
	(*common.TimeRange)(nil),      // 12: microsegment.common.TimeRange
	(*common.ReportResponse)(nil), // 13: microsegment.common.ReportResponse
}
var file_alert_alert_proto_depIdxs = []int32{
	0,  // 0: microsegment.alert.SecurityAlert.level:type_name -> microsegment.alert.AlertLevel
	1,  // 1: microsegment.alert.SecurityAlert.type:type_name -> microsegment.alert.AlertType
	10, // 2: microsegment.alert.SecurityAlert.process_info:type_name -> microsegment.flow.ProcessInfo
	11, // 3: microsegment.alert.SecurityAlert.flow_event:type_name -> microsegment.flow.FlowEvent
	9,  // 4: microsegment.alert.SecurityAlert.metadata:type_name -> microsegment.alert.SecurityAlert.MetadataEntry
	12, // 5: microsegment.alert.AlertQuery.time_range:type_name -> microsegment.common.TimeRange
	0,  // 6: microsegment.alert.AlertQuery.min_level:type_name -> microsegment.alert.AlertLevel
	1,  // 7: microsegment.alert.AlertQuery.type:type_name -> microsegment.alert.AlertType
	2,  // 8: microsegment.alert.AlertQueryResponse.alerts:type_name -> microsegment.alert.SecurityAlert
	12, // 9: microsegment.alert.AlertSummaryRequest.time_range:type_name -> microsegment.common.TimeRange
	0,  // 10: microsegment.alert.AlertSummaryRequest.min_level:type_name -> microsegment.alert.AlertLevel
	7,  // 11: microsegment.alert.AlertSummary.type_stats:type_name -> microsegment.alert.AlertTypeStats
	8,  // 12: microsegment.alert.AlertSummary.top_processes:type_name -> microsegment.alert.ProcessAlertStats
	1,  // 13: microsegment.alert.AlertTypeStats.type:type_name -> microsegment.alert.AlertType
	0,  // 14: microsegment.alert.ProcessAlertStats.max_level:type_name -> microsegment.alert.AlertLevel
	2,  // 15: microsegment.alert.AlertService.ReportAlerts:input_type -> microsegment.alert.SecurityAlert
	3,  // 16: microsegment.alert.AlertService.QueryAlerts:input_type -> microsegment.alert.AlertQuery
	5,  // 17: microsegment.alert.AlertService.GetAlertSummary:input_type -> microsegment.alert.AlertSummaryRequest
	13, // 18: microsegment.alert.AlertService.ReportAlerts:output_type -> microsegment.common.ReportResponse
	4,  // 19: microsegment.alert.AlertService.QueryAlerts:output_type -> microsegment.alert.AlertQueryResponse
	6,  // 20: microsegment.alert.AlertService.GetAlertSummary:output_type -> microsegment.alert.AlertSummary
	18, // [18:21] is the sub-list for method output_type
	15, // [15:18] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_alert_alert_proto_init() }
func file_alert_alert_proto_init() {
	if File_alert_alert_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alert_alert_proto_rawDesc), len(file_alert_alert_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_alert_alert_proto_goTypes,
		DependencyIndexes: file_alert_alert_proto_depIdxs,
		EnumInfos:         file_alert_alert_proto_enumTypes,
		MessageInfos:      file_alert_alert_proto_msgTypes,
	}.Build()
	File_alert_alert_proto = out.File
	file_alert_alert_proto_goTypes = nil
	file_alert_alert_proto_depIdxs = nil
}
