// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: alert/alert.proto

package alert

import (
	context "context"
	common "github.com/haolipeng/ebpf-based-microsegment/api/proto/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AlertService_ReportAlerts_FullMethodName    = "/microsegment.alert.AlertService/ReportAlerts"
	AlertService_QueryAlerts_FullMethodName     = "/microsegment.alert.AlertService/QueryAlerts"
	AlertService_GetAlertSummary_FullMethodName = "/microsegment.alert.AlertService/GetAlertSummary"
)

// AlertServiceClient is the client API for AlertService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AlertService handles security alert reporting and querying
type AlertServiceClient interface {
	// ReportAlerts accepts a stream of security alerts from agents
	ReportAlerts(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SecurityAlert, common.ReportResponse], error)
	// QueryAlerts returns alerts matching the given criteria
	QueryAlerts(ctx context.Context, in *AlertQuery, opts ...grpc.CallOption) (*AlertQueryResponse, error)
	// GetAlertSummary returns aggregated alert statistics
	GetAlertSummary(ctx context.Context, in *AlertSummaryRequest, opts ...grpc.CallOption) (*AlertSummary, error)
}

type alertServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAlertServiceClient(cc grpc.ClientConnInterface) AlertServiceClient {
	return &alertServiceClient{cc}
}

func (c *alertServiceClient) ReportAlerts(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SecurityAlert, common.ReportResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AlertService_ServiceDesc.Streams[0], AlertService_ReportAlerts_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SecurityAlert, common.ReportResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AlertService_ReportAlertsClient = grpc.ClientStreamingClient[SecurityAlert, common.ReportResponse]

func (c *alertServiceClient) QueryAlerts(ctx context.Context, in *AlertQuery, opts ...grpc.CallOption) (*AlertQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlertQueryResponse)
	err := c.cc.Invoke(ctx, AlertService_QueryAlerts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertServiceClient) GetAlertSummary(ctx context.Context, in *AlertSummaryRequest, opts ...grpc.CallOption) (*AlertSummary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlertSummary)
	err := c.cc.Invoke(ctx, AlertService_GetAlertSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlertServiceServer is the server API for AlertService service.
// All implementations must embed UnimplementedAlertServiceServer
// for forward compatibility.
//
// AlertService handles security alert reporting and querying
type AlertServiceServer interface {
	// ReportAlerts accepts a stream of security alerts from agents
	ReportAlerts(grpc.ClientStreamingServer[SecurityAlert, common.ReportResponse]) error
	// QueryAlerts returns alerts matching the given criteria
	QueryAlerts(context.Context, *AlertQuery) (*AlertQueryResponse, error)
	// GetAlertSummary returns aggregated alert statistics
	GetAlertSummary(context.Context, *AlertSummaryRequest) (*AlertSummary, error)
	mustEmbedUnimplementedAlertServiceServer()
}

// UnimplementedAlertServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAlertServiceServer struct{}

func (UnimplementedAlertServiceServer) ReportAlerts(grpc.ClientStreamingServer[SecurityAlert, common.ReportResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ReportAlerts not implemented")
}
func (UnimplementedAlertServiceServer) QueryAlerts(context.Context, *AlertQuery) (*AlertQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryAlerts not implemented")
}
func (UnimplementedAlertServiceServer) GetAlertSummary(context.Context, *AlertSummaryRequest) (*AlertSummary, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAlertSummary not implemented")
}
func (UnimplementedAlertServiceServer) mustEmbedUnimplementedAlertServiceServer() {}
func (UnimplementedAlertServiceServer) testEmbeddedByValue()                      {}

// UnsafeAlertServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlertServiceServer will
// result in compilation errors.
type UnsafeAlertServiceServer interface {
	mustEmbedUnimplementedAlertServiceServer()
}

func RegisterAlertServiceServer(s grpc.ServiceRegistrar, srv AlertServiceServer) {
	// If the following call pancis, it indicates UnimplementedAlertServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AlertService_ServiceDesc, srv)
}

func _AlertService_ReportAlerts_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AlertServiceServer).ReportAlerts(&grpc.GenericServerStream[SecurityAlert, common.ReportResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AlertService_ReportAlertsServer = grpc.ClientStreamingServer[SecurityAlert, common.ReportResponse]

func _AlertService_QueryAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertServiceServer).QueryAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertService_QueryAlerts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertServiceServer).QueryAlerts(ctx, req.(*AlertQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertService_GetAlertSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertServiceServer).GetAlertSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertService_GetAlertSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertServiceServer).GetAlertSummary(ctx, req.(*AlertSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AlertService_ServiceDesc is the grpc.ServiceDesc for AlertService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AlertService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "microsegment.alert.AlertService",
	HandlerType: (*AlertServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryAlerts",
			Handler:    _AlertService_QueryAlerts_Handler,
		},
		{
			MethodName: "GetAlertSummary",
			Handler:    _AlertService_GetAlertSummary_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportAlerts",
			Handler:       _AlertService_ReportAlerts_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "alert/alert.proto",
}
