// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Protocol represents network protocol types
// Uses IANA protocol numbers where applicable
type Protocol int32

const (
	// Unknown or unspecified protocol
	Protocol_PROTOCOL_UNKNOWN Protocol = 0
	// Internet Control Message Protocol
	Protocol_PROTOCOL_ICMP Protocol = 1
	// Transmission Control Protocol
	Protocol_PROTOCOL_TCP Protocol = 6
	// User Datagram Protocol
	Protocol_PROTOCOL_UDP Protocol = 17
	// Match any protocol (wildcard)
	Protocol_PROTOCOL_ANY Protocol = 255
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0:   "PROTOCOL_UNKNOWN",
		1:   "PROTOCOL_ICMP",
		6:   "PROTOCOL_TCP",
		17:  "PROTOCOL_UDP",
		255: "PROTOCOL_ANY",
	}
	Protocol_value = map[string]int32{
		"PROTOCOL_UNKNOWN": 0,
		"PROTOCOL_ICMP":    1,
		"PROTOCOL_TCP":     6,
		"PROTOCOL_UDP":     17,
		"PROTOCOL_ANY":     255,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

// PolicyAction defines the action to take when a policy rule matches
type PolicyAction int32

const (
	// Unknown or unspecified action
	PolicyAction_ACTION_UNKNOWN PolicyAction = 0
	// Allow the traffic
	PolicyAction_ACTION_ALLOW PolicyAction = 1
	// Deny/block the traffic
	PolicyAction_ACTION_DENY PolicyAction = 2
	// Log the traffic (may be combined with allow/deny)
	PolicyAction_ACTION_LOG PolicyAction = 3
)

// Enum value maps for PolicyAction.
var (
	PolicyAction_name = map[int32]string{
		0: "ACTION_UNKNOWN",
		1: "ACTION_ALLOW",
		2: "ACTION_DENY",
		3: "ACTION_LOG",
	}
	PolicyAction_value = map[string]int32{
		"ACTION_UNKNOWN": 0,
		"ACTION_ALLOW":   1,
		"ACTION_DENY":    2,
		"ACTION_LOG":     3,
	}
)

func (x PolicyAction) Enum() *PolicyAction {
	p := new(PolicyAction)
	*p = x
	return p
}

func (x PolicyAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PolicyAction) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (PolicyAction) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x PolicyAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PolicyAction.Descriptor instead.
func (PolicyAction) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

// FlowEventType indicates the type of flow event being reported
type FlowEventType int32

const (
	// Unknown event type
	FlowEventType_EVENT_UNKNOWN FlowEventType = 0
	// New flow established
	FlowEventType_EVENT_NEW FlowEventType = 1
	// Existing flow updated (stats refresh)
	FlowEventType_EVENT_UPDATE FlowEventType = 2
	// Flow closed normally
	FlowEventType_EVENT_CLOSED FlowEventType = 3
	// Flow timed out
	FlowEventType_EVENT_TIMEOUT FlowEventType = 4
)

// Enum value maps for FlowEventType.
var (
	FlowEventType_name = map[int32]string{
		0: "EVENT_UNKNOWN",
		1: "EVENT_NEW",
		2: "EVENT_UPDATE",
		3: "EVENT_CLOSED",
		4: "EVENT_TIMEOUT",
	}
	FlowEventType_value = map[string]int32{
		"EVENT_UNKNOWN": 0,
		"EVENT_NEW":     1,
		"EVENT_UPDATE":  2,
		"EVENT_CLOSED":  3,
		"EVENT_TIMEOUT": 4,
	}
)

func (x FlowEventType) Enum() *FlowEventType {
	p := new(FlowEventType)
	*p = x
	return p
}

func (x FlowEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FlowEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[2].Descriptor()
}

func (FlowEventType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[2]
}

func (x FlowEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FlowEventType.Descriptor instead.
func (FlowEventType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

// FlowDirection indicates the direction of traffic relative to the agent
type FlowDirection int32

const (
	// Unknown direction
	FlowDirection_DIRECTION_UNKNOWN FlowDirection = 0
	// Traffic coming into the workload
	FlowDirection_DIRECTION_INGRESS FlowDirection = 1
	// Traffic going out from the workload
	FlowDirection_DIRECTION_EGRESS FlowDirection = 2
)

// Enum value maps for FlowDirection.
var (
	FlowDirection_name = map[int32]string{
		0: "DIRECTION_UNKNOWN",
		1: "DIRECTION_INGRESS",
		2: "DIRECTION_EGRESS",
	}
	FlowDirection_value = map[string]int32{
		"DIRECTION_UNKNOWN": 0,
		"DIRECTION_INGRESS": 1,
		"DIRECTION_EGRESS":  2,
	}
)

func (x FlowDirection) Enum() *FlowDirection {
	p := new(FlowDirection)
	*p = x
	return p
}

func (x FlowDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FlowDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[3].Descriptor()
}

func (FlowDirection) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[3]
}

func (x FlowDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FlowDirection.Descriptor instead.
func (FlowDirection) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

// FlowState represents the current state of a flow
type FlowState int32

const (
	// Unknown state
	FlowState_STATE_UNKNOWN FlowState = 0
	// Flow is active
	FlowState_STATE_ACTIVE FlowState = 1
	// Flow is closed
	FlowState_STATE_CLOSED FlowState = 2
	// Flow timed out
	FlowState_STATE_TIMEOUT FlowState = 3
)

// Enum value maps for FlowState.
var (
	FlowState_name = map[int32]string{
		0: "STATE_UNKNOWN",
		1: "STATE_ACTIVE",
		2: "STATE_CLOSED",
		3: "STATE_TIMEOUT",
	}
	FlowState_value = map[string]int32{
		"STATE_UNKNOWN": 0,
		"STATE_ACTIVE":  1,
		"STATE_CLOSED":  2,
		"STATE_TIMEOUT": 3,
	}
)

func (x FlowState) Enum() *FlowState {
	p := new(FlowState)
	*p = x
	return p
}

func (x FlowState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FlowState) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[4].Descriptor()
}

func (FlowState) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[4]
}

func (x FlowState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FlowState.Descriptor instead.
func (FlowState) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

// ReportResponse is the standard response for reporting operations
// Used by FlowService.ReportFlowEvents and PolicyService.ReportPolicyStats
type ReportResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the report was successfully received
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Human-readable message (error details or success confirmation)
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Number of items accepted and processed
	AcceptedCount uint32 `protobuf:"varint,3,opt,name=accepted_count,json=acceptedCount,proto3" json:"accepted_count,omitempty"`
	// Number of items rejected (validation failures, duplicates, etc.)
	RejectedCount uint32 `protobuf:"varint,4,opt,name=rejected_count,json=rejectedCount,proto3" json:"rejected_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *ReportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReportResponse) GetAcceptedCount() uint32 {
	if x != nil {
		return x.AcceptedCount
	}
	return 0
}

func (x *ReportResponse) GetRejectedCount() uint32 {
	if x != nil {
		return x.RejectedCount
	}
	return 0
}

// TimeRange represents a time interval for queries
type TimeRange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Start time in Unix nanoseconds (inclusive)
	StartTime int64 `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// End time in Unix nanoseconds (exclusive)
	EndTime       int64 `protobuf:"varint,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *TimeRange) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *TimeRange) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x13microsegment.common\"\x92\x01\n" +
	"\x0eReportResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0eaccepted_count\x18\x03 \x01(\rR\racceptedCount\x12%\n" +
	"\x0erejected_count\x18\x04 \x01(\rR\rrejectedCount\"E\n" +
	"\tTimeRange\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\x03R\aendTime*j\n" +
	"\bProtocol\x12\x14\n" +
	"\x10PROTOCOL_UNKNOWN\x10\x00\x12\x11\n" +
	"\rPROTOCOL_ICMP\x10\x01\x12\x10\n" +
	"\fPROTOCOL_TCP\x10\x06\x12\x10\n" +
	"\fPROTOCOL_UDP\x10\x11\x12\x11\n" +
	"\fPROTOCOL_ANY\x10\xff\x01*U\n" +
	"\fPolicyAction\x12\x12\n" +
	"\x0eACTION_UNKNOWN\x10\x00\x12\x10\n" +
	"\fACTION_ALLOW\x10\x01\x12\x0f\n" +
	"\vACTION_DENY\x10\x02\x12\x0e\n" +
	"\n" +
	"ACTION_LOG\x10\x03*h\n" +
	"\rFlowEventType\x12\x11\n" +
	"\rEVENT_UNKNOWN\x10\x00\x12\r\n" +
	"\tEVENT_NEW\x10\x01\x12\x10\n" +
	"\fEVENT_UPDATE\x10\x02\x12\x10\n" +
	"\fEVENT_CLOSED\x10\x03\x12\x11\n" +
	"\rEVENT_TIMEOUT\x10\x04*S\n" +
	"\rFlowDirection\x12\x15\n" +
	"\x11DIRECTION_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11DIRECTION_INGRESS\x10\x01\x12\x14\n" +
	"\x10DIRECTION_EGRESS\x10\x02*U\n" +
	"\tFlowState\x12\x11\n" +
	"\rSTATE_UNKNOWN\x10\x00\x12\x10\n" +
	"\fSTATE_ACTIVE\x10\x01\x12\x10\n" +
	"\fSTATE_CLOSED\x10\x02\x12\x11\n" +
	"\rSTATE_TIMEOUT\x10\x03B/Z-github.com/ebpf-microsegment/src/proto/commonb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_proto_goTypes = []any{
	(Protocol)(0),          // 0: microsegment.common.Protocol
	(PolicyAction)(0),      // 1: microsegment.common.PolicyAction
	(FlowEventType)(0),     // 2: microsegment.common.FlowEventType
	(FlowDirection)(0),     // 3: microsegment.common.FlowDirection
	(FlowState)(0),         // 4: microsegment.common.FlowState
	(*ReportResponse)(nil), // 5: microsegment.common.ReportResponse
	(*TimeRange)(nil),      // 6: microsegment.common.TimeRange
}
var file_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
