// SPDX-License-Identifier: GPL-2.0 OR BSD-3-Clause
/* Process-level policy matching logic (Issue #47)
 *
 * This header file contains process-aware policy matching logic.
 * It extends the network-only policy matching to support process-level policies.
 *
 * Main features:
 * - get_current_process_info(): Get current process PID and comm
 * - lookup_process_cache(): Query process_info_map for cached process info
 * - matches_wildcard_with_process(): Check if flow + process matches wildcard policy
 * - fill_flow_event_process_fields(): Populate flow_event with process context
 *
 * Prerequisites (must be completed before including this header):
 * 1. Include common_types.h for basic types
 * 2. Include process_monitor.h for process_cache_entry definition
 * 3. Define process_info_map (from Task #46)
 *
 * Integration notes:
 * - This file extends policy_match.h with process awareness
 * - Process path matching is deferred to userspace (Task #48)
 * - Only process_name (comm) is matched in kernel space
 */

#ifndef __PROCESS_POLICY_MATCH_H__
#define __PROCESS_POLICY_MATCH_H__

/* Process information structure for kernel-space matching
 * Subset of process_cache_entry optimized for policy matching
 */
struct process_match_info {
    __u32 pid;                      // Process ID
    char comm[16];                  // Process command name
    char container_id[64];          // Container ID (from cache)
    __u64 exec_time;                // Process execution timestamp
    bool cache_hit;                 // Whether cache lookup succeeded
};

/* get_current_process_info - Get current process PID and command name
 *
 * @info: Output parameter to store process information
 *
 * This function retrieves the process context for the current network packet.
 * It obtains PID from bpf_get_current_pid_tgid() and comm from bpf_get_current_comm().
 *
 * Note: This only works for packets generated by local processes.
 * For forwarded packets, PID will be 0 (kernel context).
 */
static __always_inline void get_current_process_info(struct process_match_info *info)
{
    // Get process ID (TGID = thread group ID = process ID)
    __u64 pid_tgid = bpf_get_current_pid_tgid();
    info->pid = pid_tgid >> 32;  // Upper 32 bits = TGID (PID)

    // Get process command name (max 16 bytes)
    bpf_get_current_comm(&info->comm, sizeof(info->comm));

    // Initialize other fields
    info->container_id[0] = '\0';
    info->exec_time = 0;
    info->cache_hit = false;
}

/* lookup_process_cache - Query process_info_map for cached process information
 *
 * @info: Process match info structure (PID must be set)
 * @process_info_map_ptr: Pointer to process_info_map
 *
 * Returns: true if cache hit, false otherwise
 *
 * This function queries the process_info_map created by Task #46 to retrieve
 * cached process metadata (container ID, exec time).
 *
 * Cache hit conditions:
 * - PID exists in process_info_map
 * - exec_time matches (validates PID hasn't been reused)
 *
 * On cache miss, only PID and comm are available.
 */
static __always_inline bool lookup_process_cache(
    struct process_match_info *info,
    void *process_info_map_ptr)
{
    // Skip lookup for kernel context (PID = 0)
    if (info->pid == 0)
        return false;

    // Query process_info_map
    struct process_cache_entry *cached = bpf_map_lookup_elem(
        process_info_map_ptr, &info->pid);

    if (!cached)
        return false;

    // Verify process identity (prevent PID reuse issues)
    // If exec_time differs, this PID has been reused by a new process
    if (cached->exec_time != info->exec_time && info->exec_time != 0)
        return false;

    // Copy cached data
    __builtin_memcpy(info->container_id, cached->container_id,
                     sizeof(info->container_id));
    info->exec_time = cached->exec_time;
    info->cache_hit = true;

    return true;
}

/* matches_wildcard_with_process - Check if flow + process matches wildcard policy
 *
 * @key: Flow 5-tuple key
 * @proc: Process match info
 * @wildcard: Wildcard policy rule
 * @direction: Packet direction (POLICY_DIR_INGRESS or POLICY_DIR_EGRESS)
 *
 * Returns: true if flow + process matches policy, false otherwise
 *
 * Matching logic (all conditions must be true):
 * 1. Network matching (src_ip, dst_ip, src_port, dst_port, protocol, direction)
 * 2. Process matching: process_name == "" (any) OR process_name == comm
 *
 * Priority semantics:
 * - Policies with process_name set have higher priority
 * - Network-only policies (process_name == "") match any process
 *
 * Note: Process path matching is NOT performed here (see Task #48).
 */
static __always_inline bool matches_wildcard_with_process(
    struct flow_key *key,
    struct process_match_info *proc,
    struct wildcard_policy *wildcard,
    __u8 direction)
{
    // First, check network-level matching (existing logic from policy_match.h)

    // Direction matching
    if (wildcard->direction != POLICY_DIR_ANY &&
        wildcard->direction != direction)
        return false;

    // Source IP matching (IPv6 format: 4 x 32-bit words)
    #pragma unroll
    for (int i = 0; i < 4; i++) {
        if ((key->src_ip[i] & wildcard->src_ip_mask[i]) !=
            (wildcard->src_ip[i] & wildcard->src_ip_mask[i]))
            return false;
    }

    // Destination IP matching
    #pragma unroll
    for (int i = 0; i < 4; i++) {
        if ((key->dst_ip[i] & wildcard->dst_ip_mask[i]) !=
            (wildcard->dst_ip[i] & wildcard->dst_ip_mask[i]))
            return false;
    }

    // Source port matching (0 = match any port)
    if (wildcard->src_port != 0 && key->src_port != wildcard->src_port)
        return false;

    // Destination port matching
    if (wildcard->dst_port != 0 && key->dst_port != wildcard->dst_port)
        return false;

    // Protocol matching (0 = match any protocol)
    if (wildcard->protocol != 0 && key->protocol != wildcard->protocol)
        return false;

    // VLAN ID matching (0 = match any VLAN)
    if (wildcard->vlan_id != 0 && key->vlan_id != wildcard->vlan_id)
        return false;

    // NEW: Process name matching (Issue #47)
    // Empty string "" means match any process (network-only policy)
    // Non-empty string must exactly match process comm
    if (wildcard->process_name[0] != '\0') {
        // Process-level policy: must match process name
        if (__builtin_memcmp(wildcard->process_name, proc->comm,
                             sizeof(wildcard->process_name)) != 0)
            return false;
    }

    // All conditions matched
    return true;
}

/* lookup_policy_action_with_process - Process-aware policy lookup
 *
 * @key: Flow 5-tuple key
 * @proc: Process match info
 * @direction: Packet direction (POLICY_DIR_INGRESS or POLICY_DIR_EGRESS)
 * @rule_id: Output parameter - matched rule ID
 * @policy_map_ptr: Pointer to policy_map
 * @wildcard_policy_map_ptr: Pointer to wildcard_policy_map
 *
 * Returns: Policy action (POLICY_ACTION_ALLOW or POLICY_ACTION_DENY)
 *
 * Policy lookup strategy with process awareness:
 * 1. Fast path: Exact match - O(1) hash lookup policy_map
 *    (Note: Exact match doesn't support process fields yet, network-only)
 * 2. Slow path: Wildcard match with process - linear scan wildcard_policy_map
 *    - Prioritize policies with process_name set
 *    - Among matched policies, choose highest priority
 * 3. Default: Allow if no match
 *
 * Priority rules:
 * - Process + Network policy (priority + process_name bonus)
 * - Network-only policy (priority only)
 * - Default ALLOW
 */
static __always_inline __u8 lookup_policy_action_with_process(
    struct flow_key *key,
    struct process_match_info *proc,
    __u8 direction,
    __u32 *rule_id,
    void *policy_map_ptr,
    void *wildcard_policy_map_ptr)
{
    // ===== Fast path: Exact match (network-only) =====
    // TODO: Future optimization - add process-aware exact match map

    struct policy_key pkey = {
        .src_port = key->src_port,
        .dst_port = key->dst_port,
        .protocol = key->protocol,
        .direction = direction,
        .ip_version = key->ip_version,
        .vlan_id = key->vlan_id,
        .pad = 0,
        .pad2 = 0,
    };

    // Copy IP addresses
    #pragma unroll
    for (int i = 0; i < 4; i++) {
        pkey.src_ip[i] = key->src_ip[i];
        pkey.dst_ip[i] = key->dst_ip[i];
    }

    // Try direction-specific network-only policy
    struct policy_value *policy = bpf_map_lookup_elem(policy_map_ptr, &pkey);
    if (policy) {
        policy->hit_count += 1;
        *rule_id = policy->rule_id;
        return policy->action;
    }

    // Try bi-directional network-only policy
    pkey.direction = POLICY_DIR_ANY;
    policy = bpf_map_lookup_elem(policy_map_ptr, &pkey);
    if (policy) {
        policy->hit_count += 1;
        *rule_id = policy->rule_id;
        return policy->action;
    }

    // ===== Slow path: Wildcard match with process =====
    struct wildcard_policy *wildcard;
    struct wildcard_policy *best_match = NULL;
    __u16 best_priority = 0;
    bool best_has_process = false;

    // Scan wildcard policies (max 50 entries)
    #pragma unroll
    for (__u32 i = 0; i < 50; i++) {  // MAX_WILDCARD_LOOP
        __u32 idx = i;
        if (idx >= MAX_ENTRIES_WILDCARD_POLICY)
            break;

        wildcard = bpf_map_lookup_elem(wildcard_policy_map_ptr, &idx);
        if (!wildcard)
            continue;

        // Early stop on empty slot
        if (wildcard->rule_id == 0)
            break;

        // Check if this policy matches (network + process)
        if (!matches_wildcard_with_process(key, proc, wildcard, direction))
            continue;

        // Determine if this policy has process constraint
        bool has_process = (wildcard->process_name[0] != '\0');

        // Priority comparison with process-awareness:
        // 1. Policies with process_name are always preferred
        // 2. Among same category, higher priority wins
        bool is_better = false;
        if (has_process && !best_has_process) {
            // Process policy beats network-only policy
            is_better = true;
        } else if (has_process == best_has_process) {
            // Same category: compare priority
            is_better = (wildcard->priority > best_priority);
        }

        if (!best_match || is_better) {
            best_match = wildcard;
            best_priority = wildcard->priority;
            best_has_process = has_process;
        }
    }

    if (best_match) {
        *rule_id = best_match->rule_id;
        return best_match->action;
    }

    // ===== Default policy: Allow =====
    *rule_id = 0;
    return POLICY_ACTION_ALLOW;
}

/* fill_flow_event_process_fields - Populate flow_event with process context
 *
 * @event: Flow event structure to populate
 * @proc: Process match info
 *
 * This function fills the process-related fields in flow_event:
 * - process_name: Process command name (comm)
 * - pid: Process ID
 * - container_id: Container ID (if cache hit)
 * - process_exec_time: Process execution timestamp (if cache hit)
 *
 * If process info is unavailable (PID = 0 or cache miss):
 * - process_name is set to empty string
 * - pid is set to 0
 * - container_id is set to empty string
 * - process_exec_time is set to 0
 */
static __always_inline void fill_flow_event_process_fields(
    struct flow_event *event,
    struct process_match_info *proc)
{
    // Fill process fields
    __builtin_memcpy(event->process_name, proc->comm,
                     sizeof(event->process_name));
    event->pid = proc->pid;
    __builtin_memcpy(event->container_id, proc->container_id,
                     sizeof(event->container_id));
    event->process_exec_time = proc->exec_time;

    // Note: If cache_hit = false, container_id and exec_time will be zero/empty
    // Userspace (Task #48) will resolve these fields by querying /proc
}

#endif /* __PROCESS_POLICY_MATCH_H__ */
