// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: agent/agent.proto

package agent

import (
	_ "github.com/haolipeng/ebpf-based-microsegment/api/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AgentCommandType defines available agent commands
type AgentCommandType int32

const (
	// Unknown command
	AgentCommandType_COMMAND_UNKNOWN AgentCommandType = 0
	// Request full policy sync
	AgentCommandType_COMMAND_SYNC_POLICIES AgentCommandType = 1
	// Request full status report
	AgentCommandType_COMMAND_REPORT_STATUS AgentCommandType = 2
	// Reload configuration
	AgentCommandType_COMMAND_RELOAD_CONFIG AgentCommandType = 3
	// Restart agent
	AgentCommandType_COMMAND_RESTART AgentCommandType = 4
	// Shutdown agent
	AgentCommandType_COMMAND_SHUTDOWN AgentCommandType = 5
	// Enable debug mode
	AgentCommandType_COMMAND_ENABLE_DEBUG AgentCommandType = 6
	// Disable debug mode
	AgentCommandType_COMMAND_DISABLE_DEBUG AgentCommandType = 7
)

// Enum value maps for AgentCommandType.
var (
	AgentCommandType_name = map[int32]string{
		0: "COMMAND_UNKNOWN",
		1: "COMMAND_SYNC_POLICIES",
		2: "COMMAND_REPORT_STATUS",
		3: "COMMAND_RELOAD_CONFIG",
		4: "COMMAND_RESTART",
		5: "COMMAND_SHUTDOWN",
		6: "COMMAND_ENABLE_DEBUG",
		7: "COMMAND_DISABLE_DEBUG",
	}
	AgentCommandType_value = map[string]int32{
		"COMMAND_UNKNOWN":       0,
		"COMMAND_SYNC_POLICIES": 1,
		"COMMAND_REPORT_STATUS": 2,
		"COMMAND_RELOAD_CONFIG": 3,
		"COMMAND_RESTART":       4,
		"COMMAND_SHUTDOWN":      5,
		"COMMAND_ENABLE_DEBUG":  6,
		"COMMAND_DISABLE_DEBUG": 7,
	}
)

func (x AgentCommandType) Enum() *AgentCommandType {
	p := new(AgentCommandType)
	*p = x
	return p
}

func (x AgentCommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentCommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_agent_proto_enumTypes[0].Descriptor()
}

func (AgentCommandType) Type() protoreflect.EnumType {
	return &file_agent_agent_proto_enumTypes[0]
}

func (x AgentCommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentCommandType.Descriptor instead.
func (AgentCommandType) EnumDescriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{0}
}

// AgentStatus represents the current state of an agent
type AgentStatus int32

const (
	// Unknown status
	AgentStatus_STATUS_UNKNOWN AgentStatus = 0
	// Agent is starting up
	AgentStatus_STATUS_STARTING AgentStatus = 1
	// Agent is running normally
	AgentStatus_STATUS_RUNNING AgentStatus = 2
	// Agent is degraded (some features not working)
	AgentStatus_STATUS_DEGRADED AgentStatus = 3
	// Agent is stopping
	AgentStatus_STATUS_STOPPING AgentStatus = 4
	// Agent has encountered an error
	AgentStatus_STATUS_ERROR AgentStatus = 5
)

// Enum value maps for AgentStatus.
var (
	AgentStatus_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_STARTING",
		2: "STATUS_RUNNING",
		3: "STATUS_DEGRADED",
		4: "STATUS_STOPPING",
		5: "STATUS_ERROR",
	}
	AgentStatus_value = map[string]int32{
		"STATUS_UNKNOWN":  0,
		"STATUS_STARTING": 1,
		"STATUS_RUNNING":  2,
		"STATUS_DEGRADED": 3,
		"STATUS_STOPPING": 4,
		"STATUS_ERROR":    5,
	}
)

func (x AgentStatus) Enum() *AgentStatus {
	p := new(AgentStatus)
	*p = x
	return p
}

func (x AgentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_agent_proto_enumTypes[1].Descriptor()
}

func (AgentStatus) Type() protoreflect.EnumType {
	return &file_agent_agent_proto_enumTypes[1]
}

func (x AgentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentStatus.Descriptor instead.
func (AgentStatus) EnumDescriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{1}
}

// RegisterRequest is sent when an agent first connects to the server
type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique agent ID (typically hostname or UUID)
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Hostname of the machine running the agent
	Hostname string `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Agent version (e.g., "1.0.0")
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// Network interface being monitored
	Interface string `protobuf:"bytes,4,opt,name=interface,proto3" json:"interface,omitempty"`
	// IP addresses on this host
	IpAddresses []string `protobuf:"bytes,5,rep,name=ip_addresses,json=ipAddresses,proto3" json:"ip_addresses,omitempty"`
	// Operating system (e.g., "Linux", "Ubuntu 22.04")
	Os string `protobuf:"bytes,6,opt,name=os,proto3" json:"os,omitempty"`
	// Kernel version (e.g., "5.15.0-58-generic")
	KernelVersion string `protobuf:"bytes,7,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	// Agent start time (Unix nanoseconds)
	StartTime int64 `protobuf:"varint,8,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Agent capabilities (features supported)
	Capabilities  *AgentCapabilities `protobuf:"bytes,9,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_agent_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *RegisterRequest) GetIpAddresses() []string {
	if x != nil {
		return x.IpAddresses
	}
	return nil
}

func (x *RegisterRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *RegisterRequest) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *RegisterRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *RegisterRequest) GetCapabilities() *AgentCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// AgentCapabilities describes features supported by the agent
type AgentCapabilities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Supports eBPF flow tracking
	FlowTracking bool `protobuf:"varint,1,opt,name=flow_tracking,json=flowTracking,proto3" json:"flow_tracking,omitempty"`
	// Supports policy enforcement in eBPF
	PolicyEnforcement bool `protobuf:"varint,2,opt,name=policy_enforcement,json=policyEnforcement,proto3" json:"policy_enforcement,omitempty"`
	// Supports label-based policies
	LabelBasedPolicies bool `protobuf:"varint,3,opt,name=label_based_policies,json=labelBasedPolicies,proto3" json:"label_based_policies,omitempty"`
	// Supports streaming flow events
	FlowStreaming bool `protobuf:"varint,4,opt,name=flow_streaming,json=flowStreaming,proto3" json:"flow_streaming,omitempty"`
	// Supports policy statistics reporting
	PolicyStats bool `protobuf:"varint,5,opt,name=policy_stats,json=policyStats,proto3" json:"policy_stats,omitempty"`
	// Supports IPv6
	Ipv6Support   bool `protobuf:"varint,6,opt,name=ipv6_support,json=ipv6Support,proto3" json:"ipv6_support,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCapabilities) Reset() {
	*x = AgentCapabilities{}
	mi := &file_agent_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCapabilities) ProtoMessage() {}

func (x *AgentCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCapabilities.ProtoReflect.Descriptor instead.
func (*AgentCapabilities) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentCapabilities) GetFlowTracking() bool {
	if x != nil {
		return x.FlowTracking
	}
	return false
}

func (x *AgentCapabilities) GetPolicyEnforcement() bool {
	if x != nil {
		return x.PolicyEnforcement
	}
	return false
}

func (x *AgentCapabilities) GetLabelBasedPolicies() bool {
	if x != nil {
		return x.LabelBasedPolicies
	}
	return false
}

func (x *AgentCapabilities) GetFlowStreaming() bool {
	if x != nil {
		return x.FlowStreaming
	}
	return false
}

func (x *AgentCapabilities) GetPolicyStats() bool {
	if x != nil {
		return x.PolicyStats
	}
	return false
}

func (x *AgentCapabilities) GetIpv6Support() bool {
	if x != nil {
		return x.Ipv6Support
	}
	return false
}

// RegisterResponse is the server's response to agent registration
type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether registration was successful
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Human-readable message (error details or welcome message)
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Server version (e.g., "1.0.0")
	ServerVersion string `protobuf:"bytes,3,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	// Server timestamp (Unix nanoseconds)
	ServerTime int64 `protobuf:"varint,4,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	// Configuration for the agent
	Config        *AgentConfig `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_agent_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *RegisterResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *RegisterResponse) GetConfig() *AgentConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// AgentConfig contains configuration parameters for the agent
type AgentConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Heartbeat interval in seconds (default: 30)
	HeartbeatInterval uint32 `protobuf:"varint,1,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"`
	// Statistics reporting interval in seconds (default: 60)
	StatsInterval uint32 `protobuf:"varint,2,opt,name=stats_interval,json=statsInterval,proto3" json:"stats_interval,omitempty"`
	// Flow batch size for streaming (default: 100)
	FlowBatchSize uint32 `protobuf:"varint,3,opt,name=flow_batch_size,json=flowBatchSize,proto3" json:"flow_batch_size,omitempty"`
	// Flow batch timeout in seconds (default: 5)
	FlowBatchTimeout uint32 `protobuf:"varint,4,opt,name=flow_batch_timeout,json=flowBatchTimeout,proto3" json:"flow_batch_timeout,omitempty"`
	// Enable debug logging
	DebugMode bool `protobuf:"varint,5,opt,name=debug_mode,json=debugMode,proto3" json:"debug_mode,omitempty"`
	// Custom configuration parameters
	CustomConfig  map[string]string `protobuf:"bytes,6,rep,name=custom_config,json=customConfig,proto3" json:"custom_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentConfig) Reset() {
	*x = AgentConfig{}
	mi := &file_agent_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfig) ProtoMessage() {}

func (x *AgentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfig.ProtoReflect.Descriptor instead.
func (*AgentConfig) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{3}
}

func (x *AgentConfig) GetHeartbeatInterval() uint32 {
	if x != nil {
		return x.HeartbeatInterval
	}
	return 0
}

func (x *AgentConfig) GetStatsInterval() uint32 {
	if x != nil {
		return x.StatsInterval
	}
	return 0
}

func (x *AgentConfig) GetFlowBatchSize() uint32 {
	if x != nil {
		return x.FlowBatchSize
	}
	return 0
}

func (x *AgentConfig) GetFlowBatchTimeout() uint32 {
	if x != nil {
		return x.FlowBatchTimeout
	}
	return 0
}

func (x *AgentConfig) GetDebugMode() bool {
	if x != nil {
		return x.DebugMode
	}
	return false
}

func (x *AgentConfig) GetCustomConfig() map[string]string {
	if x != nil {
		return x.CustomConfig
	}
	return nil
}

// HeartbeatRequest is sent periodically by agents
type HeartbeatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent ID
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Heartbeat timestamp (Unix nanoseconds)
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Current agent metrics (lightweight)
	Metrics       *AgentMetrics `protobuf:"bytes,3,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_agent_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatRequest) GetMetrics() *AgentMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// AgentMetrics contains lightweight metrics for heartbeats
type AgentMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CPU usage percentage (0-100)
	CpuUsage float32 `protobuf:"fixed32,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	// Memory usage in bytes
	MemoryUsage uint64 `protobuf:"varint,2,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	// Number of packets processed since last heartbeat
	PacketsProcessed uint64 `protobuf:"varint,3,opt,name=packets_processed,json=packetsProcessed,proto3" json:"packets_processed,omitempty"`
	// Number of active network sessions/connections
	ActiveSessions uint32 `protobuf:"varint,4,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	// Number of flows reported since last heartbeat
	FlowsReported uint64 `protobuf:"varint,5,opt,name=flows_reported,json=flowsReported,proto3" json:"flows_reported,omitempty"`
	// Number of active policies
	ActivePolicies uint32 `protobuf:"varint,6,opt,name=active_policies,json=activePolicies,proto3" json:"active_policies,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentMetrics) Reset() {
	*x = AgentMetrics{}
	mi := &file_agent_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMetrics) ProtoMessage() {}

func (x *AgentMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMetrics.ProtoReflect.Descriptor instead.
func (*AgentMetrics) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{5}
}

func (x *AgentMetrics) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *AgentMetrics) GetMemoryUsage() uint64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *AgentMetrics) GetPacketsProcessed() uint64 {
	if x != nil {
		return x.PacketsProcessed
	}
	return 0
}

func (x *AgentMetrics) GetActiveSessions() uint32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *AgentMetrics) GetFlowsReported() uint64 {
	if x != nil {
		return x.FlowsReported
	}
	return 0
}

func (x *AgentMetrics) GetActivePolicies() uint32 {
	if x != nil {
		return x.ActivePolicies
	}
	return 0
}

// HeartbeatResponse is the server's response to heartbeat
type HeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether agent is healthy from server perspective
	Healthy bool `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// Human-readable message (warnings or instructions)
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Commands for the agent to execute (optional)
	Commands []*AgentCommand `protobuf:"bytes,3,rep,name=commands,proto3" json:"commands,omitempty"`
	// Server timestamp (Unix nanoseconds)
	ServerTime    int64 `protobuf:"varint,4,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_agent_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HeartbeatResponse) GetCommands() []*AgentCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *HeartbeatResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

// AgentCommand represents a command from server to agent
type AgentCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Command type
	CommandType AgentCommandType `protobuf:"varint,1,opt,name=command_type,json=commandType,proto3,enum=microsegment.agent.AgentCommandType" json:"command_type,omitempty"`
	// Unique command ID for tracking execution
	CommandId string `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// Command parameters (command-specific)
	Parameters map[string]string `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Command timeout in seconds
	Timeout       uint32 `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCommand) Reset() {
	*x = AgentCommand{}
	mi := &file_agent_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCommand) ProtoMessage() {}

func (x *AgentCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCommand.ProtoReflect.Descriptor instead.
func (*AgentCommand) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{7}
}

func (x *AgentCommand) GetCommandType() AgentCommandType {
	if x != nil {
		return x.CommandType
	}
	return AgentCommandType_COMMAND_UNKNOWN
}

func (x *AgentCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *AgentCommand) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *AgentCommand) GetTimeout() uint32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

// StatusReport contains detailed agent status
type StatusReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent ID
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Report timestamp (Unix nanoseconds)
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Current agent status
	Status AgentStatus `protobuf:"varint,3,opt,name=status,proto3,enum=microsegment.agent.AgentStatus" json:"status,omitempty"`
	// Agent uptime in seconds
	Uptime uint64 `protobuf:"varint,4,opt,name=uptime,proto3" json:"uptime,omitempty"`
	// Detailed metrics
	Metrics *AgentMetrics `protobuf:"bytes,5,opt,name=metrics,proto3" json:"metrics,omitempty"`
	// Number of policy rules currently enforced
	PolicyCount uint32 `protobuf:"varint,6,opt,name=policy_count,json=policyCount,proto3" json:"policy_count,omitempty"`
	// Current policy version
	PolicyVersion uint64 `protobuf:"varint,7,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	// Number of workloads registered on this host
	WorkloadCount uint32 `protobuf:"varint,8,opt,name=workload_count,json=workloadCount,proto3" json:"workload_count,omitempty"`
	// Error messages or warnings (if any)
	Errors []string `protobuf:"bytes,9,rep,name=errors,proto3" json:"errors,omitempty"`
	// Additional status information
	Metadata      map[string]string `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReport) Reset() {
	*x = StatusReport{}
	mi := &file_agent_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReport) ProtoMessage() {}

func (x *StatusReport) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReport.ProtoReflect.Descriptor instead.
func (*StatusReport) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{8}
}

func (x *StatusReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *StatusReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *StatusReport) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_STATUS_UNKNOWN
}

func (x *StatusReport) GetUptime() uint64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *StatusReport) GetMetrics() *AgentMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *StatusReport) GetPolicyCount() uint32 {
	if x != nil {
		return x.PolicyCount
	}
	return 0
}

func (x *StatusReport) GetPolicyVersion() uint64 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

func (x *StatusReport) GetWorkloadCount() uint32 {
	if x != nil {
		return x.WorkloadCount
	}
	return 0
}

func (x *StatusReport) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *StatusReport) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// StatusResponse is the server's acknowledgment of status report
type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether status was received successfully
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Human-readable message
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Commands to execute (if server needs agent to take action)
	Commands      []*AgentCommand `protobuf:"bytes,3,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_agent_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{9}
}

func (x *StatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StatusResponse) GetCommands() []*AgentCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

// UnregisterRequest is sent when agent is shutting down
type UnregisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent ID to unregister
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Reason for unregistering
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// Timestamp (Unix nanoseconds)
	Timestamp     int64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterRequest) Reset() {
	*x = UnregisterRequest{}
	mi := &file_agent_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterRequest) ProtoMessage() {}

func (x *UnregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterRequest.ProtoReflect.Descriptor instead.
func (*UnregisterRequest) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{10}
}

func (x *UnregisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *UnregisterRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *UnregisterRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// UnregisterResponse acknowledges agent unregistration
type UnregisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether unregistration was successful
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Human-readable message
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterResponse) Reset() {
	*x = UnregisterResponse{}
	mi := &file_agent_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterResponse) ProtoMessage() {}

func (x *UnregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterResponse.ProtoReflect.Descriptor instead.
func (*UnregisterResponse) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{11}
}

func (x *UnregisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnregisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_agent_agent_proto protoreflect.FileDescriptor

const file_agent_agent_proto_rawDesc = "" +
	"\n" +
	"\x11agent/agent.proto\x12\x12microsegment.agent\x1a\x13common/common.proto\"\xc4\x02\n" +
	"\x0fRegisterRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1c\n" +
	"\tinterface\x18\x04 \x01(\tR\tinterface\x12!\n" +
	"\fip_addresses\x18\x05 \x03(\tR\vipAddresses\x12\x0e\n" +
	"\x02os\x18\x06 \x01(\tR\x02os\x12%\n" +
	"\x0ekernel_version\x18\a \x01(\tR\rkernelVersion\x12\x1d\n" +
	"\n" +
	"start_time\x18\b \x01(\x03R\tstartTime\x12I\n" +
	"\fcapabilities\x18\t \x01(\v2%.microsegment.agent.AgentCapabilitiesR\fcapabilities\"\x86\x02\n" +
	"\x11AgentCapabilities\x12#\n" +
	"\rflow_tracking\x18\x01 \x01(\bR\fflowTracking\x12-\n" +
	"\x12policy_enforcement\x18\x02 \x01(\bR\x11policyEnforcement\x120\n" +
	"\x14label_based_policies\x18\x03 \x01(\bR\x12labelBasedPolicies\x12%\n" +
	"\x0eflow_streaming\x18\x04 \x01(\bR\rflowStreaming\x12!\n" +
	"\fpolicy_stats\x18\x05 \x01(\bR\vpolicyStats\x12!\n" +
	"\fipv6_support\x18\x06 \x01(\bR\vipv6Support\"\xc7\x01\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0eserver_version\x18\x03 \x01(\tR\rserverVersion\x12\x1f\n" +
	"\vserver_time\x18\x04 \x01(\x03R\n" +
	"serverTime\x127\n" +
	"\x06config\x18\x05 \x01(\v2\x1f.microsegment.agent.AgentConfigR\x06config\"\xf1\x02\n" +
	"\vAgentConfig\x12-\n" +
	"\x12heartbeat_interval\x18\x01 \x01(\rR\x11heartbeatInterval\x12%\n" +
	"\x0estats_interval\x18\x02 \x01(\rR\rstatsInterval\x12&\n" +
	"\x0fflow_batch_size\x18\x03 \x01(\rR\rflowBatchSize\x12,\n" +
	"\x12flow_batch_timeout\x18\x04 \x01(\rR\x10flowBatchTimeout\x12\x1d\n" +
	"\n" +
	"debug_mode\x18\x05 \x01(\bR\tdebugMode\x12V\n" +
	"\rcustom_config\x18\x06 \x03(\v21.microsegment.agent.AgentConfig.CustomConfigEntryR\fcustomConfig\x1a?\n" +
	"\x11CustomConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x01\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12:\n" +
	"\ametrics\x18\x03 \x01(\v2 .microsegment.agent.AgentMetricsR\ametrics\"\xf4\x01\n" +
	"\fAgentMetrics\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x02R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x02 \x01(\x04R\vmemoryUsage\x12+\n" +
	"\x11packets_processed\x18\x03 \x01(\x04R\x10packetsProcessed\x12'\n" +
	"\x0factive_sessions\x18\x04 \x01(\rR\x0eactiveSessions\x12%\n" +
	"\x0eflows_reported\x18\x05 \x01(\x04R\rflowsReported\x12'\n" +
	"\x0factive_policies\x18\x06 \x01(\rR\x0eactivePolicies\"\xa6\x01\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12<\n" +
	"\bcommands\x18\x03 \x03(\v2 .microsegment.agent.AgentCommandR\bcommands\x12\x1f\n" +
	"\vserver_time\x18\x04 \x01(\x03R\n" +
	"serverTime\"\xa1\x02\n" +
	"\fAgentCommand\x12G\n" +
	"\fcommand_type\x18\x01 \x01(\x0e2$.microsegment.agent.AgentCommandTypeR\vcommandType\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x12P\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v20.microsegment.agent.AgentCommand.ParametersEntryR\n" +
	"parameters\x12\x18\n" +
	"\atimeout\x18\x04 \x01(\rR\atimeout\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe6\x03\n" +
	"\fStatusReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x127\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1f.microsegment.agent.AgentStatusR\x06status\x12\x16\n" +
	"\x06uptime\x18\x04 \x01(\x04R\x06uptime\x12:\n" +
	"\ametrics\x18\x05 \x01(\v2 .microsegment.agent.AgentMetricsR\ametrics\x12!\n" +
	"\fpolicy_count\x18\x06 \x01(\rR\vpolicyCount\x12%\n" +
	"\x0epolicy_version\x18\a \x01(\x04R\rpolicyVersion\x12%\n" +
	"\x0eworkload_count\x18\b \x01(\rR\rworkloadCount\x12\x16\n" +
	"\x06errors\x18\t \x03(\tR\x06errors\x12J\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2..microsegment.agent.StatusReport.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x82\x01\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12<\n" +
	"\bcommands\x18\x03 \x03(\v2 .microsegment.agent.AgentCommandR\bcommands\"d\n" +
	"\x11UnregisterRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"H\n" +
	"\x12UnregisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\xd8\x01\n" +
	"\x10AgentCommandType\x12\x13\n" +
	"\x0fCOMMAND_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15COMMAND_SYNC_POLICIES\x10\x01\x12\x19\n" +
	"\x15COMMAND_REPORT_STATUS\x10\x02\x12\x19\n" +
	"\x15COMMAND_RELOAD_CONFIG\x10\x03\x12\x13\n" +
	"\x0fCOMMAND_RESTART\x10\x04\x12\x14\n" +
	"\x10COMMAND_SHUTDOWN\x10\x05\x12\x18\n" +
	"\x14COMMAND_ENABLE_DEBUG\x10\x06\x12\x19\n" +
	"\x15COMMAND_DISABLE_DEBUG\x10\a*\x86\x01\n" +
	"\vAgentStatus\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fSTATUS_STARTING\x10\x01\x12\x12\n" +
	"\x0eSTATUS_RUNNING\x10\x02\x12\x13\n" +
	"\x0fSTATUS_DEGRADED\x10\x03\x12\x13\n" +
	"\x0fSTATUS_STOPPING\x10\x04\x12\x10\n" +
	"\fSTATUS_ERROR\x10\x052\xfc\x02\n" +
	"\fAgentService\x12Z\n" +
	"\rRegisterAgent\x12#.microsegment.agent.RegisterRequest\x1a$.microsegment.agent.RegisterResponse\x12X\n" +
	"\tHeartbeat\x12$.microsegment.agent.HeartbeatRequest\x1a%.microsegment.agent.HeartbeatResponse\x12T\n" +
	"\fReportStatus\x12 .microsegment.agent.StatusReport\x1a\".microsegment.agent.StatusResponse\x12`\n" +
	"\x0fUnregisterAgent\x12%.microsegment.agent.UnregisterRequest\x1a&.microsegment.agent.UnregisterResponseB>Z<github.com/haolipeng/ebpf-based-microsegment/api/proto/agentb\x06proto3"

var (
	file_agent_agent_proto_rawDescOnce sync.Once
	file_agent_agent_proto_rawDescData []byte
)

func file_agent_agent_proto_rawDescGZIP() []byte {
	file_agent_agent_proto_rawDescOnce.Do(func() {
		file_agent_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_agent_proto_rawDesc), len(file_agent_agent_proto_rawDesc)))
	})
	return file_agent_agent_proto_rawDescData
}

var file_agent_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_agent_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_agent_agent_proto_goTypes = []any{
	(AgentCommandType)(0),      // 0: microsegment.agent.AgentCommandType
	(AgentStatus)(0),           // 1: microsegment.agent.AgentStatus
	(*RegisterRequest)(nil),    // 2: microsegment.agent.RegisterRequest
	(*AgentCapabilities)(nil),  // 3: microsegment.agent.AgentCapabilities
	(*RegisterResponse)(nil),   // 4: microsegment.agent.RegisterResponse
	(*AgentConfig)(nil),        // 5: microsegment.agent.AgentConfig
	(*HeartbeatRequest)(nil),   // 6: microsegment.agent.HeartbeatRequest
	(*AgentMetrics)(nil),       // 7: microsegment.agent.AgentMetrics
	(*HeartbeatResponse)(nil),  // 8: microsegment.agent.HeartbeatResponse
	(*AgentCommand)(nil),       // 9: microsegment.agent.AgentCommand
	(*StatusReport)(nil),       // 10: microsegment.agent.StatusReport
	(*StatusResponse)(nil),     // 11: microsegment.agent.StatusResponse
	(*UnregisterRequest)(nil),  // 12: microsegment.agent.UnregisterRequest
	(*UnregisterResponse)(nil), // 13: microsegment.agent.UnregisterResponse
	nil,                        // 14: microsegment.agent.AgentConfig.CustomConfigEntry
	nil,                        // 15: microsegment.agent.AgentCommand.ParametersEntry
	nil,                        // 16: microsegment.agent.StatusReport.MetadataEntry
}
var file_agent_agent_proto_depIdxs = []int32{
	3,  // 0: microsegment.agent.RegisterRequest.capabilities:type_name -> microsegment.agent.AgentCapabilities
	5,  // 1: microsegment.agent.RegisterResponse.config:type_name -> microsegment.agent.AgentConfig
	14, // 2: microsegment.agent.AgentConfig.custom_config:type_name -> microsegment.agent.AgentConfig.CustomConfigEntry
	7,  // 3: microsegment.agent.HeartbeatRequest.metrics:type_name -> microsegment.agent.AgentMetrics
	9,  // 4: microsegment.agent.HeartbeatResponse.commands:type_name -> microsegment.agent.AgentCommand
	0,  // 5: microsegment.agent.AgentCommand.command_type:type_name -> microsegment.agent.AgentCommandType
	15, // 6: microsegment.agent.AgentCommand.parameters:type_name -> microsegment.agent.AgentCommand.ParametersEntry
	1,  // 7: microsegment.agent.StatusReport.status:type_name -> microsegment.agent.AgentStatus
	7,  // 8: microsegment.agent.StatusReport.metrics:type_name -> microsegment.agent.AgentMetrics
	16, // 9: microsegment.agent.StatusReport.metadata:type_name -> microsegment.agent.StatusReport.MetadataEntry
	9,  // 10: microsegment.agent.StatusResponse.commands:type_name -> microsegment.agent.AgentCommand
	2,  // 11: microsegment.agent.AgentService.RegisterAgent:input_type -> microsegment.agent.RegisterRequest
	6,  // 12: microsegment.agent.AgentService.Heartbeat:input_type -> microsegment.agent.HeartbeatRequest
	10, // 13: microsegment.agent.AgentService.ReportStatus:input_type -> microsegment.agent.StatusReport
	12, // 14: microsegment.agent.AgentService.UnregisterAgent:input_type -> microsegment.agent.UnregisterRequest
	4,  // 15: microsegment.agent.AgentService.RegisterAgent:output_type -> microsegment.agent.RegisterResponse
	8,  // 16: microsegment.agent.AgentService.Heartbeat:output_type -> microsegment.agent.HeartbeatResponse
	11, // 17: microsegment.agent.AgentService.ReportStatus:output_type -> microsegment.agent.StatusResponse
	13, // 18: microsegment.agent.AgentService.UnregisterAgent:output_type -> microsegment.agent.UnregisterResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_agent_agent_proto_init() }
func file_agent_agent_proto_init() {
	if File_agent_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_agent_proto_rawDesc), len(file_agent_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_agent_proto_goTypes,
		DependencyIndexes: file_agent_agent_proto_depIdxs,
		EnumInfos:         file_agent_agent_proto_enumTypes,
		MessageInfos:      file_agent_agent_proto_msgTypes,
	}.Build()
	File_agent_agent_proto = out.File
	file_agent_agent_proto_goTypes = nil
	file_agent_agent_proto_depIdxs = nil
}
