-- Migration: 004_create_security_alerts
-- Description: Create security_alerts table for storing security alerts (Issue #51)
-- Author: Claude Code
-- Date: 2025-11-20

-- Create security alerts table
CREATE TABLE IF NOT EXISTS security_alerts (
    id SERIAL PRIMARY KEY,

    -- Alert identification
    alert_id VARCHAR(64) UNIQUE NOT NULL,

    -- Alert classification
    level INTEGER NOT NULL,  -- 0=INFO, 1=WARNING, 2=CRITICAL
    type INTEGER NOT NULL,   -- 0=SUSPICIOUS_PATH, 1=PRIVILEGE_ESCALATION, etc.

    -- Process information
    pid INTEGER,
    ppid INTEGER,
    uid INTEGER,
    gid INTEGER,
    comm VARCHAR(16),
    exe_path VARCHAR(1024),
    container_id VARCHAR(64),

    -- Flow information (optional)
    flow_id BIGINT,
    src_ip INET,
    dst_ip INET,
    dst_port INTEGER,
    protocol VARCHAR(16),

    -- Alert details
    reason TEXT NOT NULL,
    metadata JSONB,  -- Additional context as JSON

    -- Timestamps
    timestamp BIGINT NOT NULL,  -- Alert generation time (Unix nanoseconds)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- Agent information
    agent_id VARCHAR(64)
);

-- Add comments for documentation
COMMENT ON TABLE security_alerts IS 'Security alerts generated by process monitoring and anomaly detection (Issue #50/#51)';
COMMENT ON COLUMN security_alerts.alert_id IS 'Unique alert identifier (UUID)';
COMMENT ON COLUMN security_alerts.level IS 'Alert severity: 0=INFO, 1=WARNING, 2=CRITICAL';
COMMENT ON COLUMN security_alerts.type IS 'Alert type: 0=SUSPICIOUS_PATH, 1=PRIVILEGE_ESCALATION, 2=NAME_MISMATCH, 3=ANOMALOUS_CONNECTION, 4=DELETED_EXECUTABLE, 5=HIDDEN_EXECUTABLE';
COMMENT ON COLUMN security_alerts.exe_path IS 'Process executable path that triggered the alert';
COMMENT ON COLUMN security_alerts.flow_id IS 'Associated flow ID (if triggered by network activity)';
COMMENT ON COLUMN security_alerts.metadata IS 'Additional context stored as JSON';

-- Create indexes for efficient alert queries
CREATE INDEX idx_alerts_timestamp ON security_alerts(timestamp DESC);
CREATE INDEX idx_alerts_level ON security_alerts(level);
CREATE INDEX idx_alerts_type ON security_alerts(type);
CREATE INDEX idx_alerts_exe_path ON security_alerts(exe_path) WHERE exe_path IS NOT NULL;
CREATE INDEX idx_alerts_pid ON security_alerts(pid) WHERE pid IS NOT NULL;
CREATE INDEX idx_alerts_agent_id ON security_alerts(agent_id) WHERE agent_id IS NOT NULL;
CREATE INDEX idx_alerts_container_id ON security_alerts(container_id) WHERE container_id IS NOT NULL;

-- Create composite indexes for common queries
CREATE INDEX idx_alerts_level_time ON security_alerts(level, timestamp DESC);
CREATE INDEX idx_alerts_type_time ON security_alerts(type, timestamp DESC);

-- Create GIN index for JSONB metadata queries
CREATE INDEX idx_alerts_metadata ON security_alerts USING GIN(metadata);

-- Add check constraints
ALTER TABLE security_alerts ADD CONSTRAINT chk_alert_level CHECK (level >= 0 AND level <= 2);
ALTER TABLE security_alerts ADD CONSTRAINT chk_alert_type CHECK (type >= 0 AND type <= 5);

-- Add foreign key constraint to flows table (if flow_id is provided)
-- Note: This is a soft reference, flows may be deleted independently
-- ALTER TABLE security_alerts ADD CONSTRAINT fk_alerts_flow FOREIGN KEY (flow_id) REFERENCES flows(id) ON DELETE SET NULL;
