// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: flow.proto

package flow

import (
	context "context"
	common "github.com/ebpf-microsegment/src/proto/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FlowService_ReportFlowEvents_FullMethodName = "/microsegment.flow.FlowService/ReportFlowEvents"
	FlowService_QueryFlows_FullMethodName       = "/microsegment.flow.FlowService/QueryFlows"
	FlowService_GetFlowSummary_FullMethodName   = "/microsegment.flow.FlowService/GetFlowSummary"
)

// FlowServiceClient is the client API for FlowService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FlowService handles flow event reporting and querying
type FlowServiceClient interface {
	// ReportFlowEvents accepts a stream of flow events from agents
	// Agents should batch events and send them periodically
	ReportFlowEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FlowEvent, common.ReportResponse], error)
	// QueryFlows returns flows matching the given criteria
	QueryFlows(ctx context.Context, in *FlowQuery, opts ...grpc.CallOption) (*FlowQueryResponse, error)
	// GetFlowSummary returns aggregated statistics for flows
	GetFlowSummary(ctx context.Context, in *FlowSummaryRequest, opts ...grpc.CallOption) (*FlowSummary, error)
}

type flowServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFlowServiceClient(cc grpc.ClientConnInterface) FlowServiceClient {
	return &flowServiceClient{cc}
}

func (c *flowServiceClient) ReportFlowEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FlowEvent, common.ReportResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FlowService_ServiceDesc.Streams[0], FlowService_ReportFlowEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FlowEvent, common.ReportResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FlowService_ReportFlowEventsClient = grpc.ClientStreamingClient[FlowEvent, common.ReportResponse]

func (c *flowServiceClient) QueryFlows(ctx context.Context, in *FlowQuery, opts ...grpc.CallOption) (*FlowQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlowQueryResponse)
	err := c.cc.Invoke(ctx, FlowService_QueryFlows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flowServiceClient) GetFlowSummary(ctx context.Context, in *FlowSummaryRequest, opts ...grpc.CallOption) (*FlowSummary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlowSummary)
	err := c.cc.Invoke(ctx, FlowService_GetFlowSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlowServiceServer is the server API for FlowService service.
// All implementations must embed UnimplementedFlowServiceServer
// for forward compatibility.
//
// FlowService handles flow event reporting and querying
type FlowServiceServer interface {
	// ReportFlowEvents accepts a stream of flow events from agents
	// Agents should batch events and send them periodically
	ReportFlowEvents(grpc.ClientStreamingServer[FlowEvent, common.ReportResponse]) error
	// QueryFlows returns flows matching the given criteria
	QueryFlows(context.Context, *FlowQuery) (*FlowQueryResponse, error)
	// GetFlowSummary returns aggregated statistics for flows
	GetFlowSummary(context.Context, *FlowSummaryRequest) (*FlowSummary, error)
	mustEmbedUnimplementedFlowServiceServer()
}

// UnimplementedFlowServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFlowServiceServer struct{}

func (UnimplementedFlowServiceServer) ReportFlowEvents(grpc.ClientStreamingServer[FlowEvent, common.ReportResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ReportFlowEvents not implemented")
}
func (UnimplementedFlowServiceServer) QueryFlows(context.Context, *FlowQuery) (*FlowQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryFlows not implemented")
}
func (UnimplementedFlowServiceServer) GetFlowSummary(context.Context, *FlowSummaryRequest) (*FlowSummary, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFlowSummary not implemented")
}
func (UnimplementedFlowServiceServer) mustEmbedUnimplementedFlowServiceServer() {}
func (UnimplementedFlowServiceServer) testEmbeddedByValue()                     {}

// UnsafeFlowServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlowServiceServer will
// result in compilation errors.
type UnsafeFlowServiceServer interface {
	mustEmbedUnimplementedFlowServiceServer()
}

func RegisterFlowServiceServer(s grpc.ServiceRegistrar, srv FlowServiceServer) {
	// If the following call pancis, it indicates UnimplementedFlowServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FlowService_ServiceDesc, srv)
}

func _FlowService_ReportFlowEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FlowServiceServer).ReportFlowEvents(&grpc.GenericServerStream[FlowEvent, common.ReportResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FlowService_ReportFlowEventsServer = grpc.ClientStreamingServer[FlowEvent, common.ReportResponse]

func _FlowService_QueryFlows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlowQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlowServiceServer).QueryFlows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlowService_QueryFlows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlowServiceServer).QueryFlows(ctx, req.(*FlowQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlowService_GetFlowSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlowSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlowServiceServer).GetFlowSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlowService_GetFlowSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlowServiceServer).GetFlowSummary(ctx, req.(*FlowSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FlowService_ServiceDesc is the grpc.ServiceDesc for FlowService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlowService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "microsegment.flow.FlowService",
	HandlerType: (*FlowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryFlows",
			Handler:    _FlowService_QueryFlows_Handler,
		},
		{
			MethodName: "GetFlowSummary",
			Handler:    _FlowService_GetFlowSummary_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportFlowEvents",
			Handler:       _FlowService_ReportFlowEvents_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "flow.proto",
}
