// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: policy.proto

package policy

import (
	context "context"
	common "github.com/ebpf-microsegment/src/proto/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PolicyService_SyncPolicies_FullMethodName      = "/microsegment.policy.PolicyService/SyncPolicies"
	PolicyService_SubscribePolicies_FullMethodName = "/microsegment.policy.PolicyService/SubscribePolicies"
	PolicyService_ReportPolicyStats_FullMethodName = "/microsegment.policy.PolicyService/ReportPolicyStats"
)

// PolicyServiceClient is the client API for PolicyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PolicyService handles policy synchronization and statistics reporting
type PolicyServiceClient interface {
	// SyncPolicies performs a full policy synchronization
	// Agents call this on startup or when they detect version mismatch
	SyncPolicies(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error)
	// SubscribePolicies subscribes to policy updates (streaming)
	// Agents receive incremental updates in real-time
	SubscribePolicies(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PolicyUpdate], error)
	// ReportPolicyStats reports policy enforcement statistics from agents
	ReportPolicyStats(ctx context.Context, in *PolicyStatsReport, opts ...grpc.CallOption) (*common.ReportResponse, error)
}

type policyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPolicyServiceClient(cc grpc.ClientConnInterface) PolicyServiceClient {
	return &policyServiceClient{cc}
}

func (c *policyServiceClient) SyncPolicies(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, PolicyService_SyncPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) SubscribePolicies(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PolicyUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PolicyService_ServiceDesc.Streams[0], PolicyService_SubscribePolicies_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, PolicyUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PolicyService_SubscribePoliciesClient = grpc.ServerStreamingClient[PolicyUpdate]

func (c *policyServiceClient) ReportPolicyStats(ctx context.Context, in *PolicyStatsReport, opts ...grpc.CallOption) (*common.ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.ReportResponse)
	err := c.cc.Invoke(ctx, PolicyService_ReportPolicyStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PolicyServiceServer is the server API for PolicyService service.
// All implementations must embed UnimplementedPolicyServiceServer
// for forward compatibility.
//
// PolicyService handles policy synchronization and statistics reporting
type PolicyServiceServer interface {
	// SyncPolicies performs a full policy synchronization
	// Agents call this on startup or when they detect version mismatch
	SyncPolicies(context.Context, *SyncRequest) (*SyncResponse, error)
	// SubscribePolicies subscribes to policy updates (streaming)
	// Agents receive incremental updates in real-time
	SubscribePolicies(*SubscribeRequest, grpc.ServerStreamingServer[PolicyUpdate]) error
	// ReportPolicyStats reports policy enforcement statistics from agents
	ReportPolicyStats(context.Context, *PolicyStatsReport) (*common.ReportResponse, error)
	mustEmbedUnimplementedPolicyServiceServer()
}

// UnimplementedPolicyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPolicyServiceServer struct{}

func (UnimplementedPolicyServiceServer) SyncPolicies(context.Context, *SyncRequest) (*SyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncPolicies not implemented")
}
func (UnimplementedPolicyServiceServer) SubscribePolicies(*SubscribeRequest, grpc.ServerStreamingServer[PolicyUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribePolicies not implemented")
}
func (UnimplementedPolicyServiceServer) ReportPolicyStats(context.Context, *PolicyStatsReport) (*common.ReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportPolicyStats not implemented")
}
func (UnimplementedPolicyServiceServer) mustEmbedUnimplementedPolicyServiceServer() {}
func (UnimplementedPolicyServiceServer) testEmbeddedByValue()                       {}

// UnsafePolicyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PolicyServiceServer will
// result in compilation errors.
type UnsafePolicyServiceServer interface {
	mustEmbedUnimplementedPolicyServiceServer()
}

func RegisterPolicyServiceServer(s grpc.ServiceRegistrar, srv PolicyServiceServer) {
	// If the following call pancis, it indicates UnimplementedPolicyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PolicyService_ServiceDesc, srv)
}

func _PolicyService_SyncPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).SyncPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyService_SyncPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).SyncPolicies(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_SubscribePolicies_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PolicyServiceServer).SubscribePolicies(m, &grpc.GenericServerStream[SubscribeRequest, PolicyUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PolicyService_SubscribePoliciesServer = grpc.ServerStreamingServer[PolicyUpdate]

func _PolicyService_ReportPolicyStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PolicyStatsReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).ReportPolicyStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyService_ReportPolicyStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).ReportPolicyStats(ctx, req.(*PolicyStatsReport))
	}
	return interceptor(ctx, in, info, handler)
}

// PolicyService_ServiceDesc is the grpc.ServiceDesc for PolicyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PolicyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "microsegment.policy.PolicyService",
	HandlerType: (*PolicyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncPolicies",
			Handler:    _PolicyService_SyncPolicies_Handler,
		},
		{
			MethodName: "ReportPolicyStats",
			Handler:    _PolicyService_ReportPolicyStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribePolicies",
			Handler:       _PolicyService_SubscribePolicies_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "policy.proto",
}
