// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: policy/policy.proto

package policy

import (
	common "github.com/haolipeng/ebpf-based-microsegment/api/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PolicyUpdateType indicates the type of policy change
type PolicyUpdateType int32

const (
	// Unknown update type
	PolicyUpdateType_UPDATE_UNKNOWN PolicyUpdateType = 0
	// New policy added
	PolicyUpdateType_UPDATE_ADD PolicyUpdateType = 1
	// Existing policy modified
	PolicyUpdateType_UPDATE_MODIFY PolicyUpdateType = 2
	// Policy deleted
	PolicyUpdateType_UPDATE_DELETE PolicyUpdateType = 3
)

// Enum value maps for PolicyUpdateType.
var (
	PolicyUpdateType_name = map[int32]string{
		0: "UPDATE_UNKNOWN",
		1: "UPDATE_ADD",
		2: "UPDATE_MODIFY",
		3: "UPDATE_DELETE",
	}
	PolicyUpdateType_value = map[string]int32{
		"UPDATE_UNKNOWN": 0,
		"UPDATE_ADD":     1,
		"UPDATE_MODIFY":  2,
		"UPDATE_DELETE":  3,
	}
)

func (x PolicyUpdateType) Enum() *PolicyUpdateType {
	p := new(PolicyUpdateType)
	*p = x
	return p
}

func (x PolicyUpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PolicyUpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_policy_policy_proto_enumTypes[0].Descriptor()
}

func (PolicyUpdateType) Type() protoreflect.EnumType {
	return &file_policy_policy_proto_enumTypes[0]
}

func (x PolicyUpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PolicyUpdateType.Descriptor instead.
func (PolicyUpdateType) EnumDescriptor() ([]byte, []int) {
	return file_policy_policy_proto_rawDescGZIP(), []int{0}
}

// ProcessMatchMode defines how process matching is performed
type ProcessMatchMode int32

const (
	// Match process by exact command name
	ProcessMatchMode_MATCH_EXACT ProcessMatchMode = 0
	// Match process by path prefix
	ProcessMatchMode_MATCH_PREFIX ProcessMatchMode = 1
	// Match process using wildcard patterns (* and ?)
	ProcessMatchMode_MATCH_WILDCARD ProcessMatchMode = 2
)

// Enum value maps for ProcessMatchMode.
var (
	ProcessMatchMode_name = map[int32]string{
		0: "MATCH_EXACT",
		1: "MATCH_PREFIX",
		2: "MATCH_WILDCARD",
	}
	ProcessMatchMode_value = map[string]int32{
		"MATCH_EXACT":    0,
		"MATCH_PREFIX":   1,
		"MATCH_WILDCARD": 2,
	}
)

func (x ProcessMatchMode) Enum() *ProcessMatchMode {
	p := new(ProcessMatchMode)
	*p = x
	return p
}

func (x ProcessMatchMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessMatchMode) Descriptor() protoreflect.EnumDescriptor {
	return file_policy_policy_proto_enumTypes[1].Descriptor()
}

func (ProcessMatchMode) Type() protoreflect.EnumType {
	return &file_policy_policy_proto_enumTypes[1]
}

func (x ProcessMatchMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessMatchMode.Descriptor instead.
func (ProcessMatchMode) EnumDescriptor() ([]byte, []int) {
	return file_policy_policy_proto_rawDescGZIP(), []int{1}
}

// SyncRequest is sent by agents to request full policy synchronization
type SyncRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent ID requesting synchronization
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Last sync timestamp (Unix nanoseconds)
	// 0 indicates first-time sync
	LastSyncTime int64 `protobuf:"varint,2,opt,name=last_sync_time,json=lastSyncTime,proto3" json:"last_sync_time,omitempty"`
	// Current policy version on the agent (0 if none)
	PolicyVersion uint64 `protobuf:"varint,3,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_policy_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_policy_policy_proto_rawDescGZIP(), []int{0}
}

func (x *SyncRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SyncRequest) GetLastSyncTime() int64 {
	if x != nil {
		return x.LastSyncTime
	}
	return 0
}

func (x *SyncRequest) GetPolicyVersion() uint64 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

// SyncResponse contains the complete policy set
type SyncResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All active policies for this agent
	Policies []*Policy `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"`
	// Current policy version on the server
	PolicyVersion uint64 `protobuf:"varint,2,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	// Server timestamp (Unix nanoseconds)
	ServerTime int64 `protobuf:"varint,3,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	// Number of policies in the response
	PolicyCount   uint32 `protobuf:"varint,4,opt,name=policy_count,json=policyCount,proto3" json:"policy_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_policy_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_policy_policy_proto_rawDescGZIP(), []int{1}
}

func (x *SyncResponse) GetPolicies() []*Policy {
	if x != nil {
		return x.Policies
	}
	return nil
}

func (x *SyncResponse) GetPolicyVersion() uint64 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

func (x *SyncResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *SyncResponse) GetPolicyCount() uint32 {
	if x != nil {
		return x.PolicyCount
	}
	return 0
}

// SubscribeRequest initiates a policy update subscription
type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent ID subscribing to updates
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Current policy version on the agent
	CurrentVersion uint64 `protobuf:"varint,2,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_policy_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_policy_policy_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SubscribeRequest) GetCurrentVersion() uint64 {
	if x != nil {
		return x.CurrentVersion
	}
	return 0
}

// PolicyUpdate represents an incremental policy change
type PolicyUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of update (add, modify, delete)
	UpdateType PolicyUpdateType `protobuf:"varint,1,opt,name=update_type,json=updateType,proto3,enum=microsegment.policy.PolicyUpdateType" json:"update_type,omitempty"`
	// The policy being updated (null for DELETE operations)
	Policy *Policy `protobuf:"bytes,2,opt,name=policy,proto3" json:"policy,omitempty"`
	// New policy version after this update
	PolicyVersion uint64 `protobuf:"varint,3,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	// Server timestamp (Unix nanoseconds)
	Timestamp     int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyUpdate) Reset() {
	*x = PolicyUpdate{}
	mi := &file_policy_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyUpdate) ProtoMessage() {}

func (x *PolicyUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_policy_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyUpdate.ProtoReflect.Descriptor instead.
func (*PolicyUpdate) Descriptor() ([]byte, []int) {
	return file_policy_policy_proto_rawDescGZIP(), []int{3}
}

func (x *PolicyUpdate) GetUpdateType() PolicyUpdateType {
	if x != nil {
		return x.UpdateType
	}
	return PolicyUpdateType_UPDATE_UNKNOWN
}

func (x *PolicyUpdate) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *PolicyUpdate) GetPolicyVersion() uint64 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

func (x *PolicyUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Policy represents a compiled network policy rule
// This is the IP-based rule format that agents enforce in eBPF
type Policy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique rule ID
	RuleId uint32 `protobuf:"varint,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	// Source IP address (CIDR notation, e.g., "10.0.1.10/32")
	SrcIp string `protobuf:"bytes,2,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	// Destination IP address (CIDR notation)
	DstIp string `protobuf:"bytes,3,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	// Source port (0 = any)
	SrcPort uint32 `protobuf:"varint,4,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	// Destination port (0 = any)
	DstPort uint32 `protobuf:"varint,5,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	// Network protocol
	Protocol common.Protocol `protobuf:"varint,6,opt,name=protocol,proto3,enum=microsegment.common.Protocol" json:"protocol,omitempty"`
	// Action to take (allow, deny, log)
	Action common.PolicyAction `protobuf:"varint,7,opt,name=action,proto3,enum=microsegment.common.PolicyAction" json:"action,omitempty"`
	// Rule priority (higher = more important, evaluated first)
	Priority uint32 `protobuf:"varint,8,opt,name=priority,proto3" json:"priority,omitempty"`
	// Rule creation timestamp (Unix nanoseconds)
	CreatedAt int64 `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Rule last update timestamp (Unix nanoseconds)
	UpdatedAt int64 `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Source labels (for informational purposes and debugging)
	SourceLabels map[string]string `protobuf:"bytes,11,rep,name=source_labels,json=sourceLabels,proto3" json:"source_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Destination labels
	DestLabels map[string]string `protobuf:"bytes,12,rep,name=dest_labels,json=destLabels,proto3" json:"dest_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Human-readable description
	Description string `protobuf:"bytes,13,opt,name=description,proto3" json:"description,omitempty"`
	// Process command name (e.g., "nginx", "curl")
	// Empty string means match all processes
	ProcessName string `protobuf:"bytes,14,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	// Process executable path prefix (e.g., "/usr/bin/", "/tmp/")
	// Empty string means match all paths
	ProcessPath string `protobuf:"bytes,15,opt,name=process_path,json=processPath,proto3" json:"process_path,omitempty"`
	// Process matching mode
	MatchMode     ProcessMatchMode `protobuf:"varint,16,opt,name=match_mode,json=matchMode,proto3,enum=microsegment.policy.ProcessMatchMode" json:"match_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_policy_policy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_policy_policy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_policy_policy_proto_rawDescGZIP(), []int{4}
}

func (x *Policy) GetRuleId() uint32 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

func (x *Policy) GetSrcIp() string {
	if x != nil {
		return x.SrcIp
	}
	return ""
}

func (x *Policy) GetDstIp() string {
	if x != nil {
		return x.DstIp
	}
	return ""
}

func (x *Policy) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *Policy) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *Policy) GetProtocol() common.Protocol {
	if x != nil {
		return x.Protocol
	}
	return common.Protocol(0)
}

func (x *Policy) GetAction() common.PolicyAction {
	if x != nil {
		return x.Action
	}
	return common.PolicyAction(0)
}

func (x *Policy) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Policy) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Policy) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Policy) GetSourceLabels() map[string]string {
	if x != nil {
		return x.SourceLabels
	}
	return nil
}

func (x *Policy) GetDestLabels() map[string]string {
	if x != nil {
		return x.DestLabels
	}
	return nil
}

func (x *Policy) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Policy) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *Policy) GetProcessPath() string {
	if x != nil {
		return x.ProcessPath
	}
	return ""
}

func (x *Policy) GetMatchMode() ProcessMatchMode {
	if x != nil {
		return x.MatchMode
	}
	return ProcessMatchMode_MATCH_EXACT
}

// PolicyStatsReport contains policy enforcement statistics from an agent
type PolicyStatsReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent ID reporting statistics
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Report timestamp (Unix nanoseconds)
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Time range covered by this report
	TimeRange *common.TimeRange `protobuf:"bytes,3,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	// Statistics for each policy rule
	PolicyStats   []*PolicyStats `protobuf:"bytes,4,rep,name=policy_stats,json=policyStats,proto3" json:"policy_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyStatsReport) Reset() {
	*x = PolicyStatsReport{}
	mi := &file_policy_policy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyStatsReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyStatsReport) ProtoMessage() {}

func (x *PolicyStatsReport) ProtoReflect() protoreflect.Message {
	mi := &file_policy_policy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyStatsReport.ProtoReflect.Descriptor instead.
func (*PolicyStatsReport) Descriptor() ([]byte, []int) {
	return file_policy_policy_proto_rawDescGZIP(), []int{5}
}

func (x *PolicyStatsReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *PolicyStatsReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PolicyStatsReport) GetTimeRange() *common.TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

func (x *PolicyStatsReport) GetPolicyStats() []*PolicyStats {
	if x != nil {
		return x.PolicyStats
	}
	return nil
}

// PolicyStats contains statistics for a single policy rule
type PolicyStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Policy rule ID
	RuleId uint32 `protobuf:"varint,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	// Number of packets matched
	PacketCount uint64 `protobuf:"varint,2,opt,name=packet_count,json=packetCount,proto3" json:"packet_count,omitempty"`
	// Number of bytes matched
	ByteCount uint64 `protobuf:"varint,3,opt,name=byte_count,json=byteCount,proto3" json:"byte_count,omitempty"`
	// Number of flows matched
	FlowCount uint64 `protobuf:"varint,4,opt,name=flow_count,json=flowCount,proto3" json:"flow_count,omitempty"`
	// Number of times rule was evaluated (hits)
	HitCount uint64 `protobuf:"varint,5,opt,name=hit_count,json=hitCount,proto3" json:"hit_count,omitempty"`
	// Last match timestamp (Unix nanoseconds)
	LastMatchTime int64 `protobuf:"varint,6,opt,name=last_match_time,json=lastMatchTime,proto3" json:"last_match_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyStats) Reset() {
	*x = PolicyStats{}
	mi := &file_policy_policy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyStats) ProtoMessage() {}

func (x *PolicyStats) ProtoReflect() protoreflect.Message {
	mi := &file_policy_policy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyStats.ProtoReflect.Descriptor instead.
func (*PolicyStats) Descriptor() ([]byte, []int) {
	return file_policy_policy_proto_rawDescGZIP(), []int{6}
}

func (x *PolicyStats) GetRuleId() uint32 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

func (x *PolicyStats) GetPacketCount() uint64 {
	if x != nil {
		return x.PacketCount
	}
	return 0
}

func (x *PolicyStats) GetByteCount() uint64 {
	if x != nil {
		return x.ByteCount
	}
	return 0
}

func (x *PolicyStats) GetFlowCount() uint64 {
	if x != nil {
		return x.FlowCount
	}
	return 0
}

func (x *PolicyStats) GetHitCount() uint64 {
	if x != nil {
		return x.HitCount
	}
	return 0
}

func (x *PolicyStats) GetLastMatchTime() int64 {
	if x != nil {
		return x.LastMatchTime
	}
	return 0
}

var File_policy_policy_proto protoreflect.FileDescriptor

const file_policy_policy_proto_rawDesc = "" +
	"\n" +
	"\x13policy/policy.proto\x12\x13microsegment.policy\x1a\x13common/common.proto\"u\n" +
	"\vSyncRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12$\n" +
	"\x0elast_sync_time\x18\x02 \x01(\x03R\flastSyncTime\x12%\n" +
	"\x0epolicy_version\x18\x03 \x01(\x04R\rpolicyVersion\"\xb2\x01\n" +
	"\fSyncResponse\x127\n" +
	"\bpolicies\x18\x01 \x03(\v2\x1b.microsegment.policy.PolicyR\bpolicies\x12%\n" +
	"\x0epolicy_version\x18\x02 \x01(\x04R\rpolicyVersion\x12\x1f\n" +
	"\vserver_time\x18\x03 \x01(\x03R\n" +
	"serverTime\x12!\n" +
	"\fpolicy_count\x18\x04 \x01(\rR\vpolicyCount\"V\n" +
	"\x10SubscribeRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12'\n" +
	"\x0fcurrent_version\x18\x02 \x01(\x04R\x0ecurrentVersion\"\xd0\x01\n" +
	"\fPolicyUpdate\x12F\n" +
	"\vupdate_type\x18\x01 \x01(\x0e2%.microsegment.policy.PolicyUpdateTypeR\n" +
	"updateType\x123\n" +
	"\x06policy\x18\x02 \x01(\v2\x1b.microsegment.policy.PolicyR\x06policy\x12%\n" +
	"\x0epolicy_version\x18\x03 \x01(\x04R\rpolicyVersion\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\xa5\x06\n" +
	"\x06Policy\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\rR\x06ruleId\x12\x15\n" +
	"\x06src_ip\x18\x02 \x01(\tR\x05srcIp\x12\x15\n" +
	"\x06dst_ip\x18\x03 \x01(\tR\x05dstIp\x12\x19\n" +
	"\bsrc_port\x18\x04 \x01(\rR\asrcPort\x12\x19\n" +
	"\bdst_port\x18\x05 \x01(\rR\adstPort\x129\n" +
	"\bprotocol\x18\x06 \x01(\x0e2\x1d.microsegment.common.ProtocolR\bprotocol\x129\n" +
	"\x06action\x18\a \x01(\x0e2!.microsegment.common.PolicyActionR\x06action\x12\x1a\n" +
	"\bpriority\x18\b \x01(\rR\bpriority\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\x12R\n" +
	"\rsource_labels\x18\v \x03(\v2-.microsegment.policy.Policy.SourceLabelsEntryR\fsourceLabels\x12L\n" +
	"\vdest_labels\x18\f \x03(\v2+.microsegment.policy.Policy.DestLabelsEntryR\n" +
	"destLabels\x12 \n" +
	"\vdescription\x18\r \x01(\tR\vdescription\x12!\n" +
	"\fprocess_name\x18\x0e \x01(\tR\vprocessName\x12!\n" +
	"\fprocess_path\x18\x0f \x01(\tR\vprocessPath\x12D\n" +
	"\n" +
	"match_mode\x18\x10 \x01(\x0e2%.microsegment.policy.ProcessMatchModeR\tmatchMode\x1a?\n" +
	"\x11SourceLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fDestLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd0\x01\n" +
	"\x11PolicyStatsReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12=\n" +
	"\n" +
	"time_range\x18\x03 \x01(\v2\x1e.microsegment.common.TimeRangeR\ttimeRange\x12C\n" +
	"\fpolicy_stats\x18\x04 \x03(\v2 .microsegment.policy.PolicyStatsR\vpolicyStats\"\xcc\x01\n" +
	"\vPolicyStats\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\rR\x06ruleId\x12!\n" +
	"\fpacket_count\x18\x02 \x01(\x04R\vpacketCount\x12\x1d\n" +
	"\n" +
	"byte_count\x18\x03 \x01(\x04R\tbyteCount\x12\x1d\n" +
	"\n" +
	"flow_count\x18\x04 \x01(\x04R\tflowCount\x12\x1b\n" +
	"\thit_count\x18\x05 \x01(\x04R\bhitCount\x12&\n" +
	"\x0flast_match_time\x18\x06 \x01(\x03R\rlastMatchTime*\\\n" +
	"\x10PolicyUpdateType\x12\x12\n" +
	"\x0eUPDATE_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"UPDATE_ADD\x10\x01\x12\x11\n" +
	"\rUPDATE_MODIFY\x10\x02\x12\x11\n" +
	"\rUPDATE_DELETE\x10\x03*I\n" +
	"\x10ProcessMatchMode\x12\x0f\n" +
	"\vMATCH_EXACT\x10\x00\x12\x10\n" +
	"\fMATCH_PREFIX\x10\x01\x12\x12\n" +
	"\x0eMATCH_WILDCARD\x10\x022\xa7\x02\n" +
	"\rPolicyService\x12S\n" +
	"\fSyncPolicies\x12 .microsegment.policy.SyncRequest\x1a!.microsegment.policy.SyncResponse\x12_\n" +
	"\x11SubscribePolicies\x12%.microsegment.policy.SubscribeRequest\x1a!.microsegment.policy.PolicyUpdate0\x01\x12`\n" +
	"\x11ReportPolicyStats\x12&.microsegment.policy.PolicyStatsReport\x1a#.microsegment.common.ReportResponseB?Z=github.com/haolipeng/ebpf-based-microsegment/api/proto/policyb\x06proto3"

var (
	file_policy_policy_proto_rawDescOnce sync.Once
	file_policy_policy_proto_rawDescData []byte
)

func file_policy_policy_proto_rawDescGZIP() []byte {
	file_policy_policy_proto_rawDescOnce.Do(func() {
		file_policy_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_policy_policy_proto_rawDesc), len(file_policy_policy_proto_rawDesc)))
	})
	return file_policy_policy_proto_rawDescData
}

var file_policy_policy_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_policy_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_policy_policy_proto_goTypes = []any{
	(PolicyUpdateType)(0),         // 0: microsegment.policy.PolicyUpdateType
	(ProcessMatchMode)(0),         // 1: microsegment.policy.ProcessMatchMode
	(*SyncRequest)(nil),           // 2: microsegment.policy.SyncRequest
	(*SyncResponse)(nil),          // 3: microsegment.policy.SyncResponse
	(*SubscribeRequest)(nil),      // 4: microsegment.policy.SubscribeRequest
	(*PolicyUpdate)(nil),          // 5: microsegment.policy.PolicyUpdate
	(*Policy)(nil),                // 6: microsegment.policy.Policy
	(*PolicyStatsReport)(nil),     // 7: microsegment.policy.PolicyStatsReport
	(*PolicyStats)(nil),           // 8: microsegment.policy.PolicyStats
	nil,                           // 9: microsegment.policy.Policy.SourceLabelsEntry
	nil,                           // 10: microsegment.policy.Policy.DestLabelsEntry
	(common.Protocol)(0),          // 11: microsegment.common.Protocol
	(common.PolicyAction)(0),      // 12: microsegment.common.PolicyAction
	(*common.TimeRange)(nil),      // 13: microsegment.common.TimeRange
	(*common.ReportResponse)(nil), // 14: microsegment.common.ReportResponse
}
var file_policy_policy_proto_depIdxs = []int32{
	6,  // 0: microsegment.policy.SyncResponse.policies:type_name -> microsegment.policy.Policy
	0,  // 1: microsegment.policy.PolicyUpdate.update_type:type_name -> microsegment.policy.PolicyUpdateType
	6,  // 2: microsegment.policy.PolicyUpdate.policy:type_name -> microsegment.policy.Policy
	11, // 3: microsegment.policy.Policy.protocol:type_name -> microsegment.common.Protocol
	12, // 4: microsegment.policy.Policy.action:type_name -> microsegment.common.PolicyAction
	9,  // 5: microsegment.policy.Policy.source_labels:type_name -> microsegment.policy.Policy.SourceLabelsEntry
	10, // 6: microsegment.policy.Policy.dest_labels:type_name -> microsegment.policy.Policy.DestLabelsEntry
	1,  // 7: microsegment.policy.Policy.match_mode:type_name -> microsegment.policy.ProcessMatchMode
	13, // 8: microsegment.policy.PolicyStatsReport.time_range:type_name -> microsegment.common.TimeRange
	8,  // 9: microsegment.policy.PolicyStatsReport.policy_stats:type_name -> microsegment.policy.PolicyStats
	2,  // 10: microsegment.policy.PolicyService.SyncPolicies:input_type -> microsegment.policy.SyncRequest
	4,  // 11: microsegment.policy.PolicyService.SubscribePolicies:input_type -> microsegment.policy.SubscribeRequest
	7,  // 12: microsegment.policy.PolicyService.ReportPolicyStats:input_type -> microsegment.policy.PolicyStatsReport
	3,  // 13: microsegment.policy.PolicyService.SyncPolicies:output_type -> microsegment.policy.SyncResponse
	5,  // 14: microsegment.policy.PolicyService.SubscribePolicies:output_type -> microsegment.policy.PolicyUpdate
	14, // 15: microsegment.policy.PolicyService.ReportPolicyStats:output_type -> microsegment.common.ReportResponse
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_policy_policy_proto_init() }
func file_policy_policy_proto_init() {
	if File_policy_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_policy_policy_proto_rawDesc), len(file_policy_policy_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_policy_policy_proto_goTypes,
		DependencyIndexes: file_policy_policy_proto_depIdxs,
		EnumInfos:         file_policy_policy_proto_enumTypes,
		MessageInfos:      file_policy_policy_proto_msgTypes,
	}.Build()
	File_policy_policy_proto = out.File
	file_policy_policy_proto_goTypes = nil
	file_policy_policy_proto_depIdxs = nil
}
