// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: flow/flow.proto

package flow

import (
	common "github.com/haolipeng/ebpf-based-microsegment/api/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FlowEvent represents a single network flow event
// Optimized for compact serialization (~48 bytes base + variable labels)
// Field numbers 1-15 use 1-byte tags (high frequency fields)
type FlowEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source IP address (4 bytes for IPv4, use fixed32 for optimization)
	SrcIp uint32 `protobuf:"fixed32,1,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	// Destination IP address (4 bytes for IPv4)
	DstIp uint32 `protobuf:"fixed32,2,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	// Source port (0 for ICMP)
	SrcPort uint32 `protobuf:"varint,3,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	// Destination port (0 for ICMP)
	DstPort uint32 `protobuf:"varint,4,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	// Network protocol
	Protocol common.Protocol `protobuf:"varint,5,opt,name=protocol,proto3,enum=microsegment.common.Protocol" json:"protocol,omitempty"`
	// Event type (new, update, closed, timeout)
	EventType common.FlowEventType `protobuf:"varint,6,opt,name=event_type,json=eventType,proto3,enum=microsegment.common.FlowEventType" json:"event_type,omitempty"`
	// Flow direction (ingress/egress)
	Direction common.FlowDirection `protobuf:"varint,7,opt,name=direction,proto3,enum=microsegment.common.FlowDirection" json:"direction,omitempty"`
	// Number of packets in this flow
	PacketCount uint64 `protobuf:"varint,8,opt,name=packet_count,json=packetCount,proto3" json:"packet_count,omitempty"`
	// Number of bytes in this flow
	ByteCount uint64 `protobuf:"varint,9,opt,name=byte_count,json=byteCount,proto3" json:"byte_count,omitempty"`
	// Timestamp in nanoseconds (Unix epoch)
	TimestampNs uint64 `protobuf:"fixed64,10,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	// Policy rule ID that matched this flow (0 if no match)
	PolicyId uint32 `protobuf:"varint,11,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	// Action taken by policy (allow, deny, log)
	PolicyAction common.PolicyAction `protobuf:"varint,12,opt,name=policy_action,json=policyAction,proto3,enum=microsegment.common.PolicyAction" json:"policy_action,omitempty"`
	// Current state of the flow
	State common.FlowState `protobuf:"varint,13,opt,name=state,proto3,enum=microsegment.common.FlowState" json:"state,omitempty"`
	// Agent ID that reported this event
	AgentId string `protobuf:"bytes,14,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Labels of the source workload
	// Field numbers 16+ use 2-byte tags (lower frequency fields)
	SourceLabels map[string]string `protobuf:"bytes,16,rep,name=source_labels,json=sourceLabels,proto3" json:"source_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Labels of the destination workload
	DestLabels map[string]string `protobuf:"bytes,17,rep,name=dest_labels,json=destLabels,proto3" json:"dest_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Process information (Issue #51 - Process-Level Policy)
	ProcessInfo   *ProcessInfo `protobuf:"bytes,18,opt,name=process_info,json=processInfo,proto3" json:"process_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowEvent) Reset() {
	*x = FlowEvent{}
	mi := &file_flow_flow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowEvent) ProtoMessage() {}

func (x *FlowEvent) ProtoReflect() protoreflect.Message {
	mi := &file_flow_flow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowEvent.ProtoReflect.Descriptor instead.
func (*FlowEvent) Descriptor() ([]byte, []int) {
	return file_flow_flow_proto_rawDescGZIP(), []int{0}
}

func (x *FlowEvent) GetSrcIp() uint32 {
	if x != nil {
		return x.SrcIp
	}
	return 0
}

func (x *FlowEvent) GetDstIp() uint32 {
	if x != nil {
		return x.DstIp
	}
	return 0
}

func (x *FlowEvent) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *FlowEvent) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *FlowEvent) GetProtocol() common.Protocol {
	if x != nil {
		return x.Protocol
	}
	return common.Protocol(0)
}

func (x *FlowEvent) GetEventType() common.FlowEventType {
	if x != nil {
		return x.EventType
	}
	return common.FlowEventType(0)
}

func (x *FlowEvent) GetDirection() common.FlowDirection {
	if x != nil {
		return x.Direction
	}
	return common.FlowDirection(0)
}

func (x *FlowEvent) GetPacketCount() uint64 {
	if x != nil {
		return x.PacketCount
	}
	return 0
}

func (x *FlowEvent) GetByteCount() uint64 {
	if x != nil {
		return x.ByteCount
	}
	return 0
}

func (x *FlowEvent) GetTimestampNs() uint64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *FlowEvent) GetPolicyId() uint32 {
	if x != nil {
		return x.PolicyId
	}
	return 0
}

func (x *FlowEvent) GetPolicyAction() common.PolicyAction {
	if x != nil {
		return x.PolicyAction
	}
	return common.PolicyAction(0)
}

func (x *FlowEvent) GetState() common.FlowState {
	if x != nil {
		return x.State
	}
	return common.FlowState(0)
}

func (x *FlowEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *FlowEvent) GetSourceLabels() map[string]string {
	if x != nil {
		return x.SourceLabels
	}
	return nil
}

func (x *FlowEvent) GetDestLabels() map[string]string {
	if x != nil {
		return x.DestLabels
	}
	return nil
}

func (x *FlowEvent) GetProcessInfo() *ProcessInfo {
	if x != nil {
		return x.ProcessInfo
	}
	return nil
}

// ProcessInfo contains information about the process that generated the flow
// This enables process-level policy enforcement and security monitoring
type ProcessInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Process ID
	Pid uint32 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	// Parent process ID
	Ppid uint32 `protobuf:"varint,2,opt,name=ppid,proto3" json:"ppid,omitempty"`
	// User ID
	Uid uint32 `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	// Group ID
	Gid uint32 `protobuf:"varint,4,opt,name=gid,proto3" json:"gid,omitempty"`
	// Process command name (truncated to 16 bytes by kernel)
	Comm string `protobuf:"bytes,5,opt,name=comm,proto3" json:"comm,omitempty"`
	// Full executable path (resolved from /proc/<pid>/exe)
	ExePath string `protobuf:"bytes,6,opt,name=exe_path,json=exePath,proto3" json:"exe_path,omitempty"`
	// Command line arguments (optional, may be expensive to collect)
	Cmdline string `protobuf:"bytes,7,opt,name=cmdline,proto3" json:"cmdline,omitempty"`
	// Process start time (Unix nanoseconds, used for PID reuse detection)
	StartTime uint64 `protobuf:"varint,8,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Marked as suspicious by security validator (Issue #50)
	IsSuspicious bool `protobuf:"varint,9,opt,name=is_suspicious,json=isSuspicious,proto3" json:"is_suspicious,omitempty"`
	// Container ID (extracted from cgroup path)
	ContainerId   string `protobuf:"bytes,10,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_flow_flow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_flow_flow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_flow_flow_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessInfo) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessInfo) GetPpid() uint32 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

func (x *ProcessInfo) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ProcessInfo) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *ProcessInfo) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

func (x *ProcessInfo) GetExePath() string {
	if x != nil {
		return x.ExePath
	}
	return ""
}

func (x *ProcessInfo) GetCmdline() string {
	if x != nil {
		return x.Cmdline
	}
	return ""
}

func (x *ProcessInfo) GetStartTime() uint64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ProcessInfo) GetIsSuspicious() bool {
	if x != nil {
		return x.IsSuspicious
	}
	return false
}

func (x *ProcessInfo) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

// FlowQuery specifies filtering criteria for flow queries
type FlowQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Time range filter
	TimeRange *common.TimeRange `protobuf:"bytes,1,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	// Filter by source IP (CIDR notation, e.g., "10.0.1.0/24")
	SrcIp string `protobuf:"bytes,2,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	// Filter by destination IP (CIDR notation)
	DstIp string `protobuf:"bytes,3,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	// Filter by source port (0 = any)
	SrcPort uint32 `protobuf:"varint,4,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	// Filter by destination port (0 = any)
	DstPort uint32 `protobuf:"varint,5,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	// Filter by protocol
	Protocol common.Protocol `protobuf:"varint,6,opt,name=protocol,proto3,enum=microsegment.common.Protocol" json:"protocol,omitempty"`
	// Filter by agent ID
	AgentId string `protobuf:"bytes,7,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Filter by policy action
	PolicyAction common.PolicyAction `protobuf:"varint,8,opt,name=policy_action,json=policyAction,proto3,enum=microsegment.common.PolicyAction" json:"policy_action,omitempty"`
	// Filter by source labels (all must match)
	SourceLabels map[string]string `protobuf:"bytes,9,rep,name=source_labels,json=sourceLabels,proto3" json:"source_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Filter by destination labels (all must match)
	DestLabels map[string]string `protobuf:"bytes,10,rep,name=dest_labels,json=destLabels,proto3" json:"dest_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Maximum number of results to return (0 = unlimited)
	Limit uint32 `protobuf:"varint,11,opt,name=limit,proto3" json:"limit,omitempty"`
	// Offset for pagination
	Offset uint32 `protobuf:"varint,12,opt,name=offset,proto3" json:"offset,omitempty"`
	// Filter by process ID (Issue #51)
	Pid uint32 `protobuf:"varint,13,opt,name=pid,proto3" json:"pid,omitempty"`
	// Filter by process name (Issue #51)
	ProcessName string `protobuf:"bytes,14,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	// Filter by process path prefix (Issue #51)
	ProcessPath string `protobuf:"bytes,15,opt,name=process_path,json=processPath,proto3" json:"process_path,omitempty"`
	// Filter by container ID (Issue #51)
	ContainerId   string `protobuf:"bytes,16,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowQuery) Reset() {
	*x = FlowQuery{}
	mi := &file_flow_flow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowQuery) ProtoMessage() {}

func (x *FlowQuery) ProtoReflect() protoreflect.Message {
	mi := &file_flow_flow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowQuery.ProtoReflect.Descriptor instead.
func (*FlowQuery) Descriptor() ([]byte, []int) {
	return file_flow_flow_proto_rawDescGZIP(), []int{2}
}

func (x *FlowQuery) GetTimeRange() *common.TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

func (x *FlowQuery) GetSrcIp() string {
	if x != nil {
		return x.SrcIp
	}
	return ""
}

func (x *FlowQuery) GetDstIp() string {
	if x != nil {
		return x.DstIp
	}
	return ""
}

func (x *FlowQuery) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *FlowQuery) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *FlowQuery) GetProtocol() common.Protocol {
	if x != nil {
		return x.Protocol
	}
	return common.Protocol(0)
}

func (x *FlowQuery) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *FlowQuery) GetPolicyAction() common.PolicyAction {
	if x != nil {
		return x.PolicyAction
	}
	return common.PolicyAction(0)
}

func (x *FlowQuery) GetSourceLabels() map[string]string {
	if x != nil {
		return x.SourceLabels
	}
	return nil
}

func (x *FlowQuery) GetDestLabels() map[string]string {
	if x != nil {
		return x.DestLabels
	}
	return nil
}

func (x *FlowQuery) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FlowQuery) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FlowQuery) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *FlowQuery) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *FlowQuery) GetProcessPath() string {
	if x != nil {
		return x.ProcessPath
	}
	return ""
}

func (x *FlowQuery) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

// FlowQueryResponse contains the results of a flow query
type FlowQueryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Matching flows
	Flows []*Flow `protobuf:"bytes,1,rep,name=flows,proto3" json:"flows,omitempty"`
	// Total count (before limit/offset)
	TotalCount uint64 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	// Whether there are more results available
	HasMore       bool `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowQueryResponse) Reset() {
	*x = FlowQueryResponse{}
	mi := &file_flow_flow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowQueryResponse) ProtoMessage() {}

func (x *FlowQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flow_flow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowQueryResponse.ProtoReflect.Descriptor instead.
func (*FlowQueryResponse) Descriptor() ([]byte, []int) {
	return file_flow_flow_proto_rawDescGZIP(), []int{3}
}

func (x *FlowQueryResponse) GetFlows() []*Flow {
	if x != nil {
		return x.Flows
	}
	return nil
}

func (x *FlowQueryResponse) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *FlowQueryResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// Flow represents a complete flow record (for query responses)
type Flow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Flow ID (database primary key)
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Source IP address (human-readable, e.g., "10.0.1.10")
	SrcIp string `protobuf:"bytes,2,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	// Destination IP address
	DstIp string `protobuf:"bytes,3,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	// Source port
	SrcPort uint32 `protobuf:"varint,4,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	// Destination port
	DstPort uint32 `protobuf:"varint,5,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	// Network protocol
	Protocol common.Protocol `protobuf:"varint,6,opt,name=protocol,proto3,enum=microsegment.common.Protocol" json:"protocol,omitempty"`
	// Flow direction
	Direction common.FlowDirection `protobuf:"varint,7,opt,name=direction,proto3,enum=microsegment.common.FlowDirection" json:"direction,omitempty"`
	// Number of packets
	PacketCount uint64 `protobuf:"varint,8,opt,name=packet_count,json=packetCount,proto3" json:"packet_count,omitempty"`
	// Number of bytes
	ByteCount uint64 `protobuf:"varint,9,opt,name=byte_count,json=byteCount,proto3" json:"byte_count,omitempty"`
	// Flow start time (Unix nanoseconds)
	StartTime int64 `protobuf:"varint,10,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Flow end time (Unix nanoseconds, 0 if still active)
	EndTime int64 `protobuf:"varint,11,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Policy rule ID
	PolicyId uint32 `protobuf:"varint,12,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	// Policy action
	PolicyAction common.PolicyAction `protobuf:"varint,13,opt,name=policy_action,json=policyAction,proto3,enum=microsegment.common.PolicyAction" json:"policy_action,omitempty"`
	// Flow state
	State common.FlowState `protobuf:"varint,14,opt,name=state,proto3,enum=microsegment.common.FlowState" json:"state,omitempty"`
	// Agent ID
	AgentId string `protobuf:"bytes,15,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Source workload labels
	SourceLabels map[string]string `protobuf:"bytes,16,rep,name=source_labels,json=sourceLabels,proto3" json:"source_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Destination workload labels
	DestLabels map[string]string `protobuf:"bytes,17,rep,name=dest_labels,json=destLabels,proto3" json:"dest_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Process information (Issue #51 - Process-Level Policy)
	ProcessInfo   *ProcessInfo `protobuf:"bytes,18,opt,name=process_info,json=processInfo,proto3" json:"process_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flow) Reset() {
	*x = Flow{}
	mi := &file_flow_flow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flow) ProtoMessage() {}

func (x *Flow) ProtoReflect() protoreflect.Message {
	mi := &file_flow_flow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flow.ProtoReflect.Descriptor instead.
func (*Flow) Descriptor() ([]byte, []int) {
	return file_flow_flow_proto_rawDescGZIP(), []int{4}
}

func (x *Flow) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Flow) GetSrcIp() string {
	if x != nil {
		return x.SrcIp
	}
	return ""
}

func (x *Flow) GetDstIp() string {
	if x != nil {
		return x.DstIp
	}
	return ""
}

func (x *Flow) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *Flow) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *Flow) GetProtocol() common.Protocol {
	if x != nil {
		return x.Protocol
	}
	return common.Protocol(0)
}

func (x *Flow) GetDirection() common.FlowDirection {
	if x != nil {
		return x.Direction
	}
	return common.FlowDirection(0)
}

func (x *Flow) GetPacketCount() uint64 {
	if x != nil {
		return x.PacketCount
	}
	return 0
}

func (x *Flow) GetByteCount() uint64 {
	if x != nil {
		return x.ByteCount
	}
	return 0
}

func (x *Flow) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Flow) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *Flow) GetPolicyId() uint32 {
	if x != nil {
		return x.PolicyId
	}
	return 0
}

func (x *Flow) GetPolicyAction() common.PolicyAction {
	if x != nil {
		return x.PolicyAction
	}
	return common.PolicyAction(0)
}

func (x *Flow) GetState() common.FlowState {
	if x != nil {
		return x.State
	}
	return common.FlowState(0)
}

func (x *Flow) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Flow) GetSourceLabels() map[string]string {
	if x != nil {
		return x.SourceLabels
	}
	return nil
}

func (x *Flow) GetDestLabels() map[string]string {
	if x != nil {
		return x.DestLabels
	}
	return nil
}

func (x *Flow) GetProcessInfo() *ProcessInfo {
	if x != nil {
		return x.ProcessInfo
	}
	return nil
}

// FlowSummaryRequest specifies parameters for flow summary query
type FlowSummaryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Time range for aggregation
	TimeRange *common.TimeRange `protobuf:"bytes,1,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	// Group by agent ID
	GroupByAgent bool `protobuf:"varint,2,opt,name=group_by_agent,json=groupByAgent,proto3" json:"group_by_agent,omitempty"`
	// Group by protocol
	GroupByProtocol bool `protobuf:"varint,3,opt,name=group_by_protocol,json=groupByProtocol,proto3" json:"group_by_protocol,omitempty"`
	// Optional filters (same as FlowQuery)
	AgentId       string            `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Protocol      common.Protocol   `protobuf:"varint,5,opt,name=protocol,proto3,enum=microsegment.common.Protocol" json:"protocol,omitempty"`
	SourceLabels  map[string]string `protobuf:"bytes,6,rep,name=source_labels,json=sourceLabels,proto3" json:"source_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DestLabels    map[string]string `protobuf:"bytes,7,rep,name=dest_labels,json=destLabels,proto3" json:"dest_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowSummaryRequest) Reset() {
	*x = FlowSummaryRequest{}
	mi := &file_flow_flow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowSummaryRequest) ProtoMessage() {}

func (x *FlowSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flow_flow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowSummaryRequest.ProtoReflect.Descriptor instead.
func (*FlowSummaryRequest) Descriptor() ([]byte, []int) {
	return file_flow_flow_proto_rawDescGZIP(), []int{5}
}

func (x *FlowSummaryRequest) GetTimeRange() *common.TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

func (x *FlowSummaryRequest) GetGroupByAgent() bool {
	if x != nil {
		return x.GroupByAgent
	}
	return false
}

func (x *FlowSummaryRequest) GetGroupByProtocol() bool {
	if x != nil {
		return x.GroupByProtocol
	}
	return false
}

func (x *FlowSummaryRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *FlowSummaryRequest) GetProtocol() common.Protocol {
	if x != nil {
		return x.Protocol
	}
	return common.Protocol(0)
}

func (x *FlowSummaryRequest) GetSourceLabels() map[string]string {
	if x != nil {
		return x.SourceLabels
	}
	return nil
}

func (x *FlowSummaryRequest) GetDestLabels() map[string]string {
	if x != nil {
		return x.DestLabels
	}
	return nil
}

// FlowSummary contains aggregated flow statistics
type FlowSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total number of flows
	TotalFlows uint64 `protobuf:"varint,1,opt,name=total_flows,json=totalFlows,proto3" json:"total_flows,omitempty"`
	// Total packets across all flows
	TotalPackets uint64 `protobuf:"varint,2,opt,name=total_packets,json=totalPackets,proto3" json:"total_packets,omitempty"`
	// Total bytes across all flows
	TotalBytes uint64 `protobuf:"varint,3,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	// Number of unique source IPs
	UniqueSrcIps uint32 `protobuf:"varint,4,opt,name=unique_src_ips,json=uniqueSrcIps,proto3" json:"unique_src_ips,omitempty"`
	// Number of unique destination IPs
	UniqueDstIps uint32 `protobuf:"varint,5,opt,name=unique_dst_ips,json=uniqueDstIps,proto3" json:"unique_dst_ips,omitempty"`
	// Protocol-level statistics
	ProtocolStats []*ProtocolStats `protobuf:"bytes,6,rep,name=protocol_stats,json=protocolStats,proto3" json:"protocol_stats,omitempty"`
	// Top source IPs by traffic volume
	TopSources []*IPStats `protobuf:"bytes,7,rep,name=top_sources,json=topSources,proto3" json:"top_sources,omitempty"`
	// Top destination IPs by traffic volume
	TopDestinations []*IPStats `protobuf:"bytes,8,rep,name=top_destinations,json=topDestinations,proto3" json:"top_destinations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FlowSummary) Reset() {
	*x = FlowSummary{}
	mi := &file_flow_flow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowSummary) ProtoMessage() {}

func (x *FlowSummary) ProtoReflect() protoreflect.Message {
	mi := &file_flow_flow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowSummary.ProtoReflect.Descriptor instead.
func (*FlowSummary) Descriptor() ([]byte, []int) {
	return file_flow_flow_proto_rawDescGZIP(), []int{6}
}

func (x *FlowSummary) GetTotalFlows() uint64 {
	if x != nil {
		return x.TotalFlows
	}
	return 0
}

func (x *FlowSummary) GetTotalPackets() uint64 {
	if x != nil {
		return x.TotalPackets
	}
	return 0
}

func (x *FlowSummary) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *FlowSummary) GetUniqueSrcIps() uint32 {
	if x != nil {
		return x.UniqueSrcIps
	}
	return 0
}

func (x *FlowSummary) GetUniqueDstIps() uint32 {
	if x != nil {
		return x.UniqueDstIps
	}
	return 0
}

func (x *FlowSummary) GetProtocolStats() []*ProtocolStats {
	if x != nil {
		return x.ProtocolStats
	}
	return nil
}

func (x *FlowSummary) GetTopSources() []*IPStats {
	if x != nil {
		return x.TopSources
	}
	return nil
}

func (x *FlowSummary) GetTopDestinations() []*IPStats {
	if x != nil {
		return x.TopDestinations
	}
	return nil
}

// ProtocolStats contains statistics for a specific protocol
type ProtocolStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Protocol type
	Protocol common.Protocol `protobuf:"varint,1,opt,name=protocol,proto3,enum=microsegment.common.Protocol" json:"protocol,omitempty"`
	// Number of flows
	FlowCount uint64 `protobuf:"varint,2,opt,name=flow_count,json=flowCount,proto3" json:"flow_count,omitempty"`
	// Total packets
	PacketCount uint64 `protobuf:"varint,3,opt,name=packet_count,json=packetCount,proto3" json:"packet_count,omitempty"`
	// Total bytes
	ByteCount     uint64 `protobuf:"varint,4,opt,name=byte_count,json=byteCount,proto3" json:"byte_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolStats) Reset() {
	*x = ProtocolStats{}
	mi := &file_flow_flow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolStats) ProtoMessage() {}

func (x *ProtocolStats) ProtoReflect() protoreflect.Message {
	mi := &file_flow_flow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolStats.ProtoReflect.Descriptor instead.
func (*ProtocolStats) Descriptor() ([]byte, []int) {
	return file_flow_flow_proto_rawDescGZIP(), []int{7}
}

func (x *ProtocolStats) GetProtocol() common.Protocol {
	if x != nil {
		return x.Protocol
	}
	return common.Protocol(0)
}

func (x *ProtocolStats) GetFlowCount() uint64 {
	if x != nil {
		return x.FlowCount
	}
	return 0
}

func (x *ProtocolStats) GetPacketCount() uint64 {
	if x != nil {
		return x.PacketCount
	}
	return 0
}

func (x *ProtocolStats) GetByteCount() uint64 {
	if x != nil {
		return x.ByteCount
	}
	return 0
}

// IPStats contains statistics for a specific IP address
type IPStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IP address (human-readable)
	IpAddress string `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// Number of flows
	FlowCount uint64 `protobuf:"varint,2,opt,name=flow_count,json=flowCount,proto3" json:"flow_count,omitempty"`
	// Total packets
	PacketCount uint64 `protobuf:"varint,3,opt,name=packet_count,json=packetCount,proto3" json:"packet_count,omitempty"`
	// Total bytes
	ByteCount uint64 `protobuf:"varint,4,opt,name=byte_count,json=byteCount,proto3" json:"byte_count,omitempty"`
	// Associated workload labels (if available)
	Labels        map[string]string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPStats) Reset() {
	*x = IPStats{}
	mi := &file_flow_flow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPStats) ProtoMessage() {}

func (x *IPStats) ProtoReflect() protoreflect.Message {
	mi := &file_flow_flow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPStats.ProtoReflect.Descriptor instead.
func (*IPStats) Descriptor() ([]byte, []int) {
	return file_flow_flow_proto_rawDescGZIP(), []int{8}
}

func (x *IPStats) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *IPStats) GetFlowCount() uint64 {
	if x != nil {
		return x.FlowCount
	}
	return 0
}

func (x *IPStats) GetPacketCount() uint64 {
	if x != nil {
		return x.PacketCount
	}
	return 0
}

func (x *IPStats) GetByteCount() uint64 {
	if x != nil {
		return x.ByteCount
	}
	return 0
}

func (x *IPStats) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_flow_flow_proto protoreflect.FileDescriptor

const file_flow_flow_proto_rawDesc = "" +
	"\n" +
	"\x0fflow/flow.proto\x12\x11microsegment.flow\x1a\x13common/common.proto\"\xb1\a\n" +
	"\tFlowEvent\x12\x15\n" +
	"\x06src_ip\x18\x01 \x01(\aR\x05srcIp\x12\x15\n" +
	"\x06dst_ip\x18\x02 \x01(\aR\x05dstIp\x12\x19\n" +
	"\bsrc_port\x18\x03 \x01(\rR\asrcPort\x12\x19\n" +
	"\bdst_port\x18\x04 \x01(\rR\adstPort\x129\n" +
	"\bprotocol\x18\x05 \x01(\x0e2\x1d.microsegment.common.ProtocolR\bprotocol\x12A\n" +
	"\n" +
	"event_type\x18\x06 \x01(\x0e2\".microsegment.common.FlowEventTypeR\teventType\x12@\n" +
	"\tdirection\x18\a \x01(\x0e2\".microsegment.common.FlowDirectionR\tdirection\x12!\n" +
	"\fpacket_count\x18\b \x01(\x04R\vpacketCount\x12\x1d\n" +
	"\n" +
	"byte_count\x18\t \x01(\x04R\tbyteCount\x12!\n" +
	"\ftimestamp_ns\x18\n" +
	" \x01(\x06R\vtimestampNs\x12\x1b\n" +
	"\tpolicy_id\x18\v \x01(\rR\bpolicyId\x12F\n" +
	"\rpolicy_action\x18\f \x01(\x0e2!.microsegment.common.PolicyActionR\fpolicyAction\x124\n" +
	"\x05state\x18\r \x01(\x0e2\x1e.microsegment.common.FlowStateR\x05state\x12\x19\n" +
	"\bagent_id\x18\x0e \x01(\tR\aagentId\x12S\n" +
	"\rsource_labels\x18\x10 \x03(\v2..microsegment.flow.FlowEvent.SourceLabelsEntryR\fsourceLabels\x12M\n" +
	"\vdest_labels\x18\x11 \x03(\v2,.microsegment.flow.FlowEvent.DestLabelsEntryR\n" +
	"destLabels\x12A\n" +
	"\fprocess_info\x18\x12 \x01(\v2\x1e.microsegment.flow.ProcessInfoR\vprocessInfo\x1a?\n" +
	"\x11SourceLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fDestLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x02\n" +
	"\vProcessInfo\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12\x12\n" +
	"\x04ppid\x18\x02 \x01(\rR\x04ppid\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\x04 \x01(\rR\x03gid\x12\x12\n" +
	"\x04comm\x18\x05 \x01(\tR\x04comm\x12\x19\n" +
	"\bexe_path\x18\x06 \x01(\tR\aexePath\x12\x18\n" +
	"\acmdline\x18\a \x01(\tR\acmdline\x12\x1d\n" +
	"\n" +
	"start_time\x18\b \x01(\x04R\tstartTime\x12#\n" +
	"\ris_suspicious\x18\t \x01(\bR\fisSuspicious\x12!\n" +
	"\fcontainer_id\x18\n" +
	" \x01(\tR\vcontainerId\"\x99\x06\n" +
	"\tFlowQuery\x12=\n" +
	"\n" +
	"time_range\x18\x01 \x01(\v2\x1e.microsegment.common.TimeRangeR\ttimeRange\x12\x15\n" +
	"\x06src_ip\x18\x02 \x01(\tR\x05srcIp\x12\x15\n" +
	"\x06dst_ip\x18\x03 \x01(\tR\x05dstIp\x12\x19\n" +
	"\bsrc_port\x18\x04 \x01(\rR\asrcPort\x12\x19\n" +
	"\bdst_port\x18\x05 \x01(\rR\adstPort\x129\n" +
	"\bprotocol\x18\x06 \x01(\x0e2\x1d.microsegment.common.ProtocolR\bprotocol\x12\x19\n" +
	"\bagent_id\x18\a \x01(\tR\aagentId\x12F\n" +
	"\rpolicy_action\x18\b \x01(\x0e2!.microsegment.common.PolicyActionR\fpolicyAction\x12S\n" +
	"\rsource_labels\x18\t \x03(\v2..microsegment.flow.FlowQuery.SourceLabelsEntryR\fsourceLabels\x12M\n" +
	"\vdest_labels\x18\n" +
	" \x03(\v2,.microsegment.flow.FlowQuery.DestLabelsEntryR\n" +
	"destLabels\x12\x14\n" +
	"\x05limit\x18\v \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\f \x01(\rR\x06offset\x12\x10\n" +
	"\x03pid\x18\r \x01(\rR\x03pid\x12!\n" +
	"\fprocess_name\x18\x0e \x01(\tR\vprocessName\x12!\n" +
	"\fprocess_path\x18\x0f \x01(\tR\vprocessPath\x12!\n" +
	"\fcontainer_id\x18\x10 \x01(\tR\vcontainerId\x1a?\n" +
	"\x11SourceLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fDestLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"~\n" +
	"\x11FlowQueryResponse\x12-\n" +
	"\x05flows\x18\x01 \x03(\v2\x17.microsegment.flow.FlowR\x05flows\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x04R\n" +
	"totalCount\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"\x86\a\n" +
	"\x04Flow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x15\n" +
	"\x06src_ip\x18\x02 \x01(\tR\x05srcIp\x12\x15\n" +
	"\x06dst_ip\x18\x03 \x01(\tR\x05dstIp\x12\x19\n" +
	"\bsrc_port\x18\x04 \x01(\rR\asrcPort\x12\x19\n" +
	"\bdst_port\x18\x05 \x01(\rR\adstPort\x129\n" +
	"\bprotocol\x18\x06 \x01(\x0e2\x1d.microsegment.common.ProtocolR\bprotocol\x12@\n" +
	"\tdirection\x18\a \x01(\x0e2\".microsegment.common.FlowDirectionR\tdirection\x12!\n" +
	"\fpacket_count\x18\b \x01(\x04R\vpacketCount\x12\x1d\n" +
	"\n" +
	"byte_count\x18\t \x01(\x04R\tbyteCount\x12\x1d\n" +
	"\n" +
	"start_time\x18\n" +
	" \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\v \x01(\x03R\aendTime\x12\x1b\n" +
	"\tpolicy_id\x18\f \x01(\rR\bpolicyId\x12F\n" +
	"\rpolicy_action\x18\r \x01(\x0e2!.microsegment.common.PolicyActionR\fpolicyAction\x124\n" +
	"\x05state\x18\x0e \x01(\x0e2\x1e.microsegment.common.FlowStateR\x05state\x12\x19\n" +
	"\bagent_id\x18\x0f \x01(\tR\aagentId\x12N\n" +
	"\rsource_labels\x18\x10 \x03(\v2).microsegment.flow.Flow.SourceLabelsEntryR\fsourceLabels\x12H\n" +
	"\vdest_labels\x18\x11 \x03(\v2'.microsegment.flow.Flow.DestLabelsEntryR\n" +
	"destLabels\x12A\n" +
	"\fprocess_info\x18\x12 \x01(\v2\x1e.microsegment.flow.ProcessInfoR\vprocessInfo\x1a?\n" +
	"\x11SourceLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fDestLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb1\x04\n" +
	"\x12FlowSummaryRequest\x12=\n" +
	"\n" +
	"time_range\x18\x01 \x01(\v2\x1e.microsegment.common.TimeRangeR\ttimeRange\x12$\n" +
	"\x0egroup_by_agent\x18\x02 \x01(\bR\fgroupByAgent\x12*\n" +
	"\x11group_by_protocol\x18\x03 \x01(\bR\x0fgroupByProtocol\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x129\n" +
	"\bprotocol\x18\x05 \x01(\x0e2\x1d.microsegment.common.ProtocolR\bprotocol\x12\\\n" +
	"\rsource_labels\x18\x06 \x03(\v27.microsegment.flow.FlowSummaryRequest.SourceLabelsEntryR\fsourceLabels\x12V\n" +
	"\vdest_labels\x18\a \x03(\v25.microsegment.flow.FlowSummaryRequest.DestLabelsEntryR\n" +
	"destLabels\x1a?\n" +
	"\x11SourceLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fDestLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8d\x03\n" +
	"\vFlowSummary\x12\x1f\n" +
	"\vtotal_flows\x18\x01 \x01(\x04R\n" +
	"totalFlows\x12#\n" +
	"\rtotal_packets\x18\x02 \x01(\x04R\ftotalPackets\x12\x1f\n" +
	"\vtotal_bytes\x18\x03 \x01(\x04R\n" +
	"totalBytes\x12$\n" +
	"\x0eunique_src_ips\x18\x04 \x01(\rR\funiqueSrcIps\x12$\n" +
	"\x0eunique_dst_ips\x18\x05 \x01(\rR\funiqueDstIps\x12G\n" +
	"\x0eprotocol_stats\x18\x06 \x03(\v2 .microsegment.flow.ProtocolStatsR\rprotocolStats\x12;\n" +
	"\vtop_sources\x18\a \x03(\v2\x1a.microsegment.flow.IPStatsR\n" +
	"topSources\x12E\n" +
	"\x10top_destinations\x18\b \x03(\v2\x1a.microsegment.flow.IPStatsR\x0ftopDestinations\"\xab\x01\n" +
	"\rProtocolStats\x129\n" +
	"\bprotocol\x18\x01 \x01(\x0e2\x1d.microsegment.common.ProtocolR\bprotocol\x12\x1d\n" +
	"\n" +
	"flow_count\x18\x02 \x01(\x04R\tflowCount\x12!\n" +
	"\fpacket_count\x18\x03 \x01(\x04R\vpacketCount\x12\x1d\n" +
	"\n" +
	"byte_count\x18\x04 \x01(\x04R\tbyteCount\"\x84\x02\n" +
	"\aIPStats\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x01 \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"flow_count\x18\x02 \x01(\x04R\tflowCount\x12!\n" +
	"\fpacket_count\x18\x03 \x01(\x04R\vpacketCount\x12\x1d\n" +
	"\n" +
	"byte_count\x18\x04 \x01(\x04R\tbyteCount\x12>\n" +
	"\x06labels\x18\x05 \x03(\v2&.microsegment.flow.IPStats.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x91\x02\n" +
	"\vFlowService\x12W\n" +
	"\x10ReportFlowEvents\x12\x1c.microsegment.flow.FlowEvent\x1a#.microsegment.common.ReportResponse(\x01\x12P\n" +
	"\n" +
	"QueryFlows\x12\x1c.microsegment.flow.FlowQuery\x1a$.microsegment.flow.FlowQueryResponse\x12W\n" +
	"\x0eGetFlowSummary\x12%.microsegment.flow.FlowSummaryRequest\x1a\x1e.microsegment.flow.FlowSummaryB=Z;github.com/haolipeng/ebpf-based-microsegment/api/proto/flowb\x06proto3"

var (
	file_flow_flow_proto_rawDescOnce sync.Once
	file_flow_flow_proto_rawDescData []byte
)

func file_flow_flow_proto_rawDescGZIP() []byte {
	file_flow_flow_proto_rawDescOnce.Do(func() {
		file_flow_flow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flow_flow_proto_rawDesc), len(file_flow_flow_proto_rawDesc)))
	})
	return file_flow_flow_proto_rawDescData
}

var file_flow_flow_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_flow_flow_proto_goTypes = []any{
	(*FlowEvent)(nil),             // 0: microsegment.flow.FlowEvent
	(*ProcessInfo)(nil),           // 1: microsegment.flow.ProcessInfo
	(*FlowQuery)(nil),             // 2: microsegment.flow.FlowQuery
	(*FlowQueryResponse)(nil),     // 3: microsegment.flow.FlowQueryResponse
	(*Flow)(nil),                  // 4: microsegment.flow.Flow
	(*FlowSummaryRequest)(nil),    // 5: microsegment.flow.FlowSummaryRequest
	(*FlowSummary)(nil),           // 6: microsegment.flow.FlowSummary
	(*ProtocolStats)(nil),         // 7: microsegment.flow.ProtocolStats
	(*IPStats)(nil),               // 8: microsegment.flow.IPStats
	nil,                           // 9: microsegment.flow.FlowEvent.SourceLabelsEntry
	nil,                           // 10: microsegment.flow.FlowEvent.DestLabelsEntry
	nil,                           // 11: microsegment.flow.FlowQuery.SourceLabelsEntry
	nil,                           // 12: microsegment.flow.FlowQuery.DestLabelsEntry
	nil,                           // 13: microsegment.flow.Flow.SourceLabelsEntry
	nil,                           // 14: microsegment.flow.Flow.DestLabelsEntry
	nil,                           // 15: microsegment.flow.FlowSummaryRequest.SourceLabelsEntry
	nil,                           // 16: microsegment.flow.FlowSummaryRequest.DestLabelsEntry
	nil,                           // 17: microsegment.flow.IPStats.LabelsEntry
	(common.Protocol)(0),          // 18: microsegment.common.Protocol
	(common.FlowEventType)(0),     // 19: microsegment.common.FlowEventType
	(common.FlowDirection)(0),     // 20: microsegment.common.FlowDirection
	(common.PolicyAction)(0),      // 21: microsegment.common.PolicyAction
	(common.FlowState)(0),         // 22: microsegment.common.FlowState
	(*common.TimeRange)(nil),      // 23: microsegment.common.TimeRange
	(*common.ReportResponse)(nil), // 24: microsegment.common.ReportResponse
}
var file_flow_flow_proto_depIdxs = []int32{
	18, // 0: microsegment.flow.FlowEvent.protocol:type_name -> microsegment.common.Protocol
	19, // 1: microsegment.flow.FlowEvent.event_type:type_name -> microsegment.common.FlowEventType
	20, // 2: microsegment.flow.FlowEvent.direction:type_name -> microsegment.common.FlowDirection
	21, // 3: microsegment.flow.FlowEvent.policy_action:type_name -> microsegment.common.PolicyAction
	22, // 4: microsegment.flow.FlowEvent.state:type_name -> microsegment.common.FlowState
	9,  // 5: microsegment.flow.FlowEvent.source_labels:type_name -> microsegment.flow.FlowEvent.SourceLabelsEntry
	10, // 6: microsegment.flow.FlowEvent.dest_labels:type_name -> microsegment.flow.FlowEvent.DestLabelsEntry
	1,  // 7: microsegment.flow.FlowEvent.process_info:type_name -> microsegment.flow.ProcessInfo
	23, // 8: microsegment.flow.FlowQuery.time_range:type_name -> microsegment.common.TimeRange
	18, // 9: microsegment.flow.FlowQuery.protocol:type_name -> microsegment.common.Protocol
	21, // 10: microsegment.flow.FlowQuery.policy_action:type_name -> microsegment.common.PolicyAction
	11, // 11: microsegment.flow.FlowQuery.source_labels:type_name -> microsegment.flow.FlowQuery.SourceLabelsEntry
	12, // 12: microsegment.flow.FlowQuery.dest_labels:type_name -> microsegment.flow.FlowQuery.DestLabelsEntry
	4,  // 13: microsegment.flow.FlowQueryResponse.flows:type_name -> microsegment.flow.Flow
	18, // 14: microsegment.flow.Flow.protocol:type_name -> microsegment.common.Protocol
	20, // 15: microsegment.flow.Flow.direction:type_name -> microsegment.common.FlowDirection
	21, // 16: microsegment.flow.Flow.policy_action:type_name -> microsegment.common.PolicyAction
	22, // 17: microsegment.flow.Flow.state:type_name -> microsegment.common.FlowState
	13, // 18: microsegment.flow.Flow.source_labels:type_name -> microsegment.flow.Flow.SourceLabelsEntry
	14, // 19: microsegment.flow.Flow.dest_labels:type_name -> microsegment.flow.Flow.DestLabelsEntry
	1,  // 20: microsegment.flow.Flow.process_info:type_name -> microsegment.flow.ProcessInfo
	23, // 21: microsegment.flow.FlowSummaryRequest.time_range:type_name -> microsegment.common.TimeRange
	18, // 22: microsegment.flow.FlowSummaryRequest.protocol:type_name -> microsegment.common.Protocol
	15, // 23: microsegment.flow.FlowSummaryRequest.source_labels:type_name -> microsegment.flow.FlowSummaryRequest.SourceLabelsEntry
	16, // 24: microsegment.flow.FlowSummaryRequest.dest_labels:type_name -> microsegment.flow.FlowSummaryRequest.DestLabelsEntry
	7,  // 25: microsegment.flow.FlowSummary.protocol_stats:type_name -> microsegment.flow.ProtocolStats
	8,  // 26: microsegment.flow.FlowSummary.top_sources:type_name -> microsegment.flow.IPStats
	8,  // 27: microsegment.flow.FlowSummary.top_destinations:type_name -> microsegment.flow.IPStats
	18, // 28: microsegment.flow.ProtocolStats.protocol:type_name -> microsegment.common.Protocol
	17, // 29: microsegment.flow.IPStats.labels:type_name -> microsegment.flow.IPStats.LabelsEntry
	0,  // 30: microsegment.flow.FlowService.ReportFlowEvents:input_type -> microsegment.flow.FlowEvent
	2,  // 31: microsegment.flow.FlowService.QueryFlows:input_type -> microsegment.flow.FlowQuery
	5,  // 32: microsegment.flow.FlowService.GetFlowSummary:input_type -> microsegment.flow.FlowSummaryRequest
	24, // 33: microsegment.flow.FlowService.ReportFlowEvents:output_type -> microsegment.common.ReportResponse
	3,  // 34: microsegment.flow.FlowService.QueryFlows:output_type -> microsegment.flow.FlowQueryResponse
	6,  // 35: microsegment.flow.FlowService.GetFlowSummary:output_type -> microsegment.flow.FlowSummary
	33, // [33:36] is the sub-list for method output_type
	30, // [30:33] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_flow_flow_proto_init() }
func file_flow_flow_proto_init() {
	if File_flow_flow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flow_flow_proto_rawDesc), len(file_flow_flow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_flow_flow_proto_goTypes,
		DependencyIndexes: file_flow_flow_proto_depIdxs,
		MessageInfos:      file_flow_flow_proto_msgTypes,
	}.Build()
	File_flow_flow_proto = out.File
	file_flow_flow_proto_goTypes = nil
	file_flow_flow_proto_depIdxs = nil
}
